### ISSUE TITLE
OCI artifact semver alignment with Helm for tags with underscore

### ISSUE THREAD

**Issue by baburciu** [fluxcd/helm-controller#1099]
[`HelmRelease` referencing a chart directly from an `OCIRepository` ](https://fluxcd.io/flux/guides/helmreleases/#using-a-chart-reference)  fails if the `OCIRepository.spec.ref.tag` contains the underscore (`_`) character.

Example:
```yaml
  apiVersion: helm.toolkit.fluxcd.io/v2
  kind: HelmRelease
  metadata:
    :
    name: monitoring-crd
    namespace: sylva-system    
    :
  spec:
    chartRef:
      kind: OCIRepository
      name: unit-monitoring-crd
    install:
      createNamespace: true
    interval: 15m
    :
  status:
    conditions:
    :
    - lastTransitionTime: "2024-10-25T22:07:45Z"
      message: artifact revision 104.1.1_up57.0.3 does not match chart version 104.1.1+up57.0.3
      observedGeneration: 2
      reason: ChartMutateError
      status: "False"
      type: Ready
---
  apiVersion: source.toolkit.fluxcd.io/v1beta2
  kind: OCIRepository
  metadata:
    :
    name: unit-monitoring-crd
    namespace: sylva-system
    :
  spec:
    interval: 60m0s
    provider: generic
    ref:
      tag: 104.1.1_up57.0.3
    timeout: 60s
    url: oci://registry.gitlab.com/sylva-projects/sylva-core/rancher-monitoring-crd
  status:
    artifact:
      :
      revision: 104.1.1_up57.0.3@sha256:85ea0013056258452ce27431392167ac036fd7fd1cb64df3a750b04851ac6d20
``` 

This happens due to https://github.com/fluxcd/helm-controller/blob/v1.0.1/internal/controller/helmrelease_controller.go#L917-L920 check, which expects the _tag_ from the _tag@digest_ formatted OCI artifact manifest digest (which [ends up as the `OCIRepository.status.artifact.revision`](https://github.com/fluxcd/source-controller/blob/v1.3.0/api/v1beta2/ocirepository_types.go#L256-L260)), to be equal to the `Chart.yaml`-defined version.

We consider [helm constraints](https://helm.sh/docs/topics/charts/#charts-and-versioning) and that ["_OCI registries don't support + as a tag character_"](https://helm.sh/docs/topics/registries/#oci-feature-deprecation-and-behavior-changes-with-v380), as [helm itself informs](https://github.com/helm/helm/blob/v3.14.4/pkg/registry/client.go#L45-L50):
> OCI artifact references (e.g. tags) do not support the plus sign (+). To support
storing semantic versions, Helm adopts the convention of changing plus (+) to
an underscore (_) in chart version tags when pushing to a registry and back to
a plus (+) when pulling from a registry.

that is why when we create OCI artifacts out of helm charts in [Project Sylva](https://sylva-projects.gitlab.io/design/hld-schema) we replace `+` with `_` from chart's version to define the artifact tag (but `Chart.yaml` contents are untouched, e.g. OCI artifact `oci://registry.gitlab.com/sylva-projects/sylva-core/rancher-monitoring-crd:104.1.1_up57.0.3` has `version: 104.1.1+up57.0.3` in  `Chart.yaml`). 

It looks like FluxCD helm-controller doesn't do the reverse (replace `_` with `+`) before doing the said validation.

Building an image on top of `fluxcd/helm-controller:v1.0.1` (we're currently using FluxCD `v2.3.0`) with below diff allows for the `HelmRelease` to be deployed.

```console
--- a/internal/controller/helmrelease_controller.go
+++ b/internal/controller/helmrelease_controller.go
@@ -915,9 +915,12 @@ func mutateChartWithSourceRevision(chart *chart.Chart, source sourcev1.Source) (
        switch {
        case strings.Contains(revision, "@"):
                tagD := strings.Split(revision, "@")
-               if len(tagD) != 2 || tagD[0] != chart.Metadata.Version {
-                       return "", fmt.Errorf("artifact revision %s does not match chart version %s", tagD[0], chart.Metadata.Version)
-               }
+               // By convention: Change underscore (_) back to plus (+) to get valid SemVer
+               // see https://github.com/helm/helm/blob/v3.14.4/pkg/registry/client.go#L45-L50
+               convertedTag := strings.ReplaceAll(tagD[0], "_", "+")
+               if len(tagD) != 2 || convertedTag != chart.Metadata.Version {
+                       return "", fmt.Errorf("artifact revision %s does not match chart version %s", convertedTag, chart.Metadata.Version)
+                }
                // algotithm are sha256, sha384, sha512 with the canonical being sha256
                // So every digest starts with a sha algorithm and a colon
                sha, err := extractDigestSubString(tagD[1])
```

I could submit a PR if this makes sense

**Comment by stefanprodan** [comment]
We use the build tag to keep track of the OCI digests, this happens in the same function here: https://github.com/fluxcd/helm-controller/blob/6085b4f02224b0fb5d6f819ed7c8d63628cc3adf/internal/controller/helmrelease_controller.go#L928

So the build tag that you set at push is overwritten by Flux in Chart.yaml, doesn't this affect the sequential upgrades in your fork?

**Comment by baburciu** [comment]
I didn't understand well why the upgrade would be affected, I'll give it a try. 
But if the point was regarding possibly duplicate use of `+` (one from the OCI tag itself post  `_` with `+` replacement and another from the leading 12 characters of the artifact manifest digest to the Chart.yaml-defined version to make sure mutable tags are detected), looks like the [SetMetadata](https://github.com/Masterminds/semver/blob/v1.5.0/version.go#L231-L241) call would only return the latter - checked [in Go playground](https://go.dev/play/p/YfaJgylTPN7). We see it in action below.
So I would think that for an upgrade from some `OCIRepository.spec.ref.tag` 104.1.2+up57.0.**2** to 104.1.2+up57.0.**3** (dummy values, [rancher charts](https://github.com/rancher/charts/tree/dev-v2.9/charts/rancher-monitoring) don't seem to have increments in that build metadata part), helm-controller would still see different values when replacing `.Chart.Version`, due to the 12 charts from different digests

<details markdown=1><summary>
hr & ocirepo status (click to expand)
</summary>

```yaml
  apiVersion: helm.toolkit.fluxcd.io/v2
  kind: HelmRelease
  metadata:
    :
    name: monitoring-crd
    namespace: sylva-system
  spec:
    chartRef:
      kind: OCIRepository
      name: unit-monitoring-crd
    interval: 15m
    releaseName: rancher-monitoring-crd
    storageNamespace: cattle-monitoring-system
    targetNamespace: cattle-monitoring-system
  status:
    conditions:
    - lastTransitionTime: "2024-10-31T09:17:22Z"
      message: Helm install succeeded for release cattle-monitoring-system/rancher-monitoring-crd.v1
        with chart rancher-monitoring-crd@104.1.2+efafa44b7261
      observedGeneration: 2
      reason: InstallSucceeded
      status: "True"
      type: Ready
---
  apiVersion: source.toolkit.fluxcd.io/v1beta2
  kind: OCIRepository
  metadata:
    :
    name: unit-monitoring-crd
    namespace: sylva-system
  spec:
    interval: 60m0s
    provider: generic
    ref:
      tag: 104.1.2_up57.0.3
    timeout: 60s
    url: oci://172.20.136.39/proxy_cache_registry.gitlab.com/sylva-projects/sylva-core/rancher-monitoring-crd
  status:
    artifact:
      digest: sha256:2b5e9fde0f5167956811364450270003013730d6fc06547e210712030626ed4b
      lastUpdateTime: "2024-10-31T09:15:49Z"
      metadata:
        catalog.cattle.io/certified: rancher
        catalog.cattle.io/hidden: "true"
        catalog.cattle.io/namespace: cattle-monitoring-system
        catalog.cattle.io/release-name: rancher-monitoring-crd
        org.opencontainers.image.created: "2024-10-21T21:11:07Z"
        org.opencontainers.image.description: Installs the CRDs for rancher-monitoring.
        org.opencontainers.image.title: rancher-monitoring-crd
        org.opencontainers.image.version: 104.1.2+up57.0.3
      path: ocirepository/sylva-system/unit-monitoring-crd/sha256:efafa44b7261a859aebfbabe54bb3e4a0b8a224a021c5fffdaf1bc916452d80d.tar.gz
      revision: 104.1.2_up57.0.3@sha256:efafa44b7261a859aebfbabe54bb3e4a0b8a224a021c5fffdaf1bc916452d80d
      size: 310847
      url: http://source-controller.flux-system.svc.cluster.local./ocirepository/sylva-system/unit-monitoring-crd/sha256:efafa44b7261a859aebfbabe54bb3e4a0b8a224a021c5fffdaf1bc916452d80d.tar.gz
    conditions:
    - lastTransitionTime: "2024-10-31T09:15:49Z"
      message: stored artifact for digest '104.1.2_up57.0.3@sha256:efafa44b7261a859aebfbabe54bb3e4a0b8a224a021c5fffdaf1bc916452d80d'
      observedGeneration: 1
      reason: Succeeded
      status: "True"
      type: Ready
    - lastTransitionTime: "2024-10-31T09:15:49Z"
      message: stored artifact for digest '104.1.2_up57.0.3@sha256:efafa44b7261a859aebfbabe54bb3e4a0b8a224a021c5fffdaf1bc916452d80d'
      observedGeneration: 1
      reason: Succeeded
      status: "True"
      type: ArtifactInStorage
    observedGeneration: 1
    url: http://source-controller.flux-system.svc.cluster.local./ocirepository/sylva-system/unit-monitoring-crd/latest.tar.gz
```

</details>
