### ISSUE TITLE
Clarification needed: Drift mode and lookup function

### ISSUE THREAD

**Issue by prog76** [fluxcd/helm-controller#1119]
In my chart I have a template like
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  configuration: |
      {{- $secret := default (dict "data" (dict)) (lookup "v1" "Secret" "default" .Values.secretRef) }}
      {{- if $secret.data }}
      username = "{{ $secret.data.username | b64dec }}"
      {{- end }}
```
My HelmRelease defined as
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test
spec:
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: test
      sourceRef:
        kind: HelmRepository
        name: test-helm
        namespace: flux-system
      version: 1.0.2
  interval: 5m
  values:
    secretRef: test
```
I expect that when I add/remove Secret "test" my ConfigMap should be updated automatically (every 5 minutes). 
Actually ConfigMap rendered only once and reflects existence of the Secret at the installation time.  
Is that correct/expected behavior?
Accordingly to [helm docs](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function) it should support server side dry-runs for lookup function.
helm-controller: v1.0.1
Thank you for your great work guys!
