### ISSUE TITLE
Range function iterates over nested objects

### ISSUE THREAD

**Issue by francoisvandenplas** [fluxcd/helm-controller#1147]
Hello,

It seems that the range function is also iterating over the nested interface

this template:
```
{{- range $index, $component := .Values }}
{{- if  (ne $index "global")  }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $index }}-cm-component
  namespace: {{ $.Values.global.namespace }}
data:
  component: |
    {{ $component | toYaml | nindent 4 }}
{{- end }}
{{- end }}
```

with these values: 
```
    global:
      namespace: app-dev
      env: dev
      scaling:
        replicas: 1
    listener:
      name: listener
      image: listener-img
      tag: develop
      process: outbound
      deployments:
        - name: xxx-listener
        - name: yyy-listener
          replicas: 1

    extractor:
      name: extractor
      image: extractor-img
      tag: developp
      process: inbound

      deployments:
        - name: xxx-extractor
          datatype: heartbeat-1
          format: AVRO
          replicas: 1
        - name: yyy-extractor
          datatype: heartbeat-2
          format: AVRO
          replicas: 1
        - name: zzz-extractor
          datatype: heartbeat-3
          format: AVRO
          replicas: 1
```
cause this error :

_error while running post render on files: may not add resource with an already registered id: ConfigMap.v1.[noGrp]/deployments-cm-component.app-dev_

The metadata.name is **deployments-cm-component**

if i add `{{- if and (ne $index "global") (ne $index "deployments") }}` , this cause this error :

_error while running post render on files: may not add resource with an already registered id: ConfigMap.v1.[noGrp]/image-cm-component.app-dev_
The metadata.name is **image-cm-component**

Is it an issue, or am i doing something wrong ?

François
