### ISSUE TITLE
Add support for CRD post-rendering (or selective CRD install)

### ISSUE THREAD

**Issue by gberche-orange** [fluxcd/helm-controller#1185]
Some helm charts such as loki abusively install outdated CRDs owned and maintained by other helm charts (e.g. [kube-prometheus-stack crds](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/charts/crds/crds)), see https://github.com/grafana/loki/issues/7488

As of ghcr.io/fluxcd/helm-controller:v1.0.1, the post renderers don't apply to CRDs 

https://github.com/fluxcd/helm-controller/blob/25c6bb691df30a3c2fd8a4b19ce65bc134158c90/internal/action/install.go#L50-L63

so the following syntax (extracted into a kustomize patch) is a no-op for CRDs

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  postRenderers:
    # Remove Prometheus CRDs abusively installed/downgraded by loki
    # For details on $patch syntax, see https://github.com/kubernetes/kubernetes/issues/122480#issuecomment-2685610615
    # and https://github.com/kubernetes-sigs/kustomize/blob/447a60903cd142948443a6bd441b2749ad643815/examples/inlinePatch.md?plain=1#L105-L124
    - kustomize:
        patches:
          - target:
              kind: CustomResourceDefinition
              name: servicemonitors.monitoring.coreos.com
            patch: |
              $patch: delete
              apiVersion: apiextensions.k8s.io/v1
              kind: CustomResourceDefinition
              metadata:
                name: DOES NOT MATTER
          - target:
              kind: CustomResourceDefinition
              name: probes.monitoring.coreos.com
            patch: |
              $patch: delete
              apiVersion: apiextensions.k8s.io/v1
              kind: CustomResourceDefinition
              metadata:
                name: DOES NOT MATTER
          - target:
              kind: CustomResourceDefinition
              name: podmonitors.monitoring.coreos.com
            patch: |
              $patch: delete
              apiVersion: apiextensions.k8s.io/v1
              kind: CustomResourceDefinition
              metadata:
                name: DOES NOT MATTER
```

It would be useful for flux helmrelease `spec.install` to either include 
* a new `postRenderers` field 
* a new `skipCrds` field [ "podmonitors.monitoring.coreos.com", "probes.monitoring.coreos.com", "servicemonitors.monitoring.coreos.com" ], to support selective CRD skip
