### ISSUE TITLE
Unable to deploy keycloak from bitnami oci repository

### ISSUE THREAD

**Issue by ChrisCavegn** [fluxcd/helm-controller#1199]
I'm trying to install keycloak via the bitnami oci repository. 

Setting up the repository seems to work:

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-keycloak
  namespace: flux-system
spec:
  secretRef:
    name: dockerhub
  interval: 12h0m0s
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
  ref:
    semver: "24.x.x"
```

`2025-03-21T10:32:55.807Z info OCIRepository/bitnami-keycloak.flux-system - stored artifact with revision '24.4.13@sha256:a6a019d1aaf593680508576f2708228c866f68237cd69c5bbce70cd97cb32e7b' from 'oci://regi
stry-1.docker.io/bitnamicharts/keycloak'`

However, the reconciliation fails with `unsupported protocol scheme "oci"`

`"level":"info","ts":"2025-03-21T11:02:21.067Z","msg":"HelmChart 'flux-system/redacted-keycloak' is not ready: chart pull error: failed to download chart for remote reference: Get \"oci://registry-1.doc
ker.io/bitnamicharts/keycloak:24.4.13\": unsupported protocol scheme \"oci\"","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"k
eycloak","namespace":"redacted"},"namespace":"redacted","name":"keycloak","reconcileID":"c0d7d8d0-422d-4746-ad04-59ca66acb5e8"}`

HelmDeploment:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: redacted
spec:
  releaseName: keycloak
  chartRef:
    kind: OCIRepository
    name: bitnami-keycloak
    namespace: flux-system
```

Used Versions:
ghcr.io/fluxcd/helm-controller:v1.2.0
ghcr.io/fluxcd/kustomize-controller:v1.5.1
ghcr.io/fluxcd/notification-controller:v1.5.0
ghcr.io/fluxcd/source-controller:v1.5.0

**Comment by stefanprodan** [comment]
The `chartRef` was added in `helm.toolkit.fluxcd.io/v2` you are using an API version from 3 years ago. Delete the HelmRelease from the cluster, then recreate it from Git using `v2`.

**Comment by ChrisCavegn** [comment]
Argh, i knew it had to be a stupid mistake

Thank you @stefanprodan!

For the sake of completeness - the following HelmRelease works as expected:

```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: redacted
spec:
  releaseName: keycloak
  chartRef:
    kind: OCIRepository
    name: bitnami-keycloak
    namespace: flux-system
```
