### ISSUE TITLE
Add CommonLabels to HelmRelease kustomize postRender

### ISSUE THREAD

**Issue by abhijith-darshan** [fluxcd/helm-controller#1217]
Currently the `postRender` in `HelmRelease` only supports `patches` and `images` fields for `kustomize`.

~~Introduce `commonLabels` and `commonAnnotations` keys supported by `kustomize` to allow setting some common labels and keys across all resources.~~

This reduces the overhead of prior knowledge of knowing the `apiVersion`, `kind`, resource naming conventions coming in from the helm chart.

This would be a huge benefit for platform teams that provide kubernetes resource abstractions by using flux underneath. It allows platform specific conventions to be applied on public Helm charts.

Update:

The existing convention of `CommonMetadata` in `kustomize-controller` is re-used here in `.spec` of `HelmRelease`  instead of adding `commonLabels` and `commonAnnotations` to `.spec.postRenderers[*].Kustomize`

**Comment by abhijith-darshan** [comment]
I have opened a PR #1223 for this issue as well.

Considering the following spec -

```yaml
spec:
  chart:
    spec:
      chart: podinfo
      interval: 10m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: '>=6.0.0 <7.0.0'
  interval: 5m
  postRenderers:
    - kustomize:
        commonAnnotations:
          fluxcd.io/foo: bar
        commonLabels:
          fluxcd.io/bar: baz
    - kustomize:
        commonAnnotations:
          fluxcd.io/bar: boo
          fluxcd.io/foo: baz # duplicate key
```

This should propagate common annotation and labels to all resources in the helm chart.

In the scenario where duplicate label keys or annotation keys are used in multiple kustomize `postRenderers` the last one wins since it is executed in order.
