### ISSUE TITLE
unable to merge value from key 'sharedSecret' in Secret 'pomerium/pomerium-config-secrets' into target path 'config.sharedSecret': unable to parse key: assignment to entry in nil map

### ISSUE THREAD

**Issue by stuartpb** [fluxcd/helm-controller#123]
I have this HelmRelease:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pomerium
  namespace: pomerium
  selfLink: /apis/helm.toolkit.fluxcd.io/v2beta1/namespaces/pomerium/helmreleases/pomerium
spec:
  chart:
    spec:
      chart: pomerium
      sourceRef:
        kind: HelmRepository
        name: pomerium
        namespace: gotk-system
      version: 13.0.0
  interval: 10m0s
  values:
    config:
      policy:
      - allowed_users:
        - github/stuartpb
        - s@stuartpb.com
        from: https://alertmanager.horn.horse
        to: http://kps-alertmanager.prometheus.svc.cluster.local:9093
      - allowed_users:
        - github/stuartpb
        - s@stuartpb.com
        from: https://prometheus.horn.horse
        to: http://kps-prometheus.prometheus.svc.cluster.local:9090
      - allowed_users:
        - github/stuartpb
        - s@stuartpb.com
        from: https://grafana.horn.horse
        pass_identity_headers: true
        to: http://kube-prometheus-stack-grafana.prometheus.svc.cluster.local
      - allowed_users:
        - github/stuartpb
        - s@stuartpb.com
        from: https://rook-ceph.horn.horse
        to: http://rook-ceph-mgr-dashboard.rook-ceph.svc.cluster.local:7000
      - allowed_users:
        - github/stuartpb
        - s@stuartpb.com
        from: https://kubernetes-dashboard.horn.horse
        tls_skip_verify: true
        to: https://kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local
      rootDomain: horn.horse
    extraEnvFrom:
    - secretRef:
        name: hornhorse-github
    forwardAuth:
      enabled: true
      internal: true
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: stuartpb-letsencrypt-staging
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/ingress.class: internal
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      secret:
        name: pomerium-hornhorse-cert
    nodeSelector:
      kubernetes.io/arch: amd64
    redis:
      enabled: true
      image:
        repository: library/redis
      master:
        persistence:
          storageClass: throwaway
      slave:
        persistence:
          storageClass: throwaway
  valuesFrom:
  - kind: Secret
    name: pomerium-config-secrets
    targetPath: config.sharedSecret
    valuesKey: sharedSecret
  - kind: Secret
    name: pomerium-config-secrets
    targetPath: config.cookieSecret
    valuesKey: cookieSecret
status:
  conditions:
  - lastTransitionTime: "2020-10-21T11:33:39Z"
    message: 'unable to merge value from key ''sharedSecret'' in Secret ''pomerium/pomerium-config-secrets''
      into target path ''config.sharedSecret'': unable to parse key: assignment to
      entry in nil map'
    reason: InitFailed
    status: "False"
    type: Ready
  failures: 1
  helmChart: gotk-system/pomerium-pomerium
  lastAttemptedRevision: 13.0.2
  lastAttemptedValuesChecksum: 5b8d69560c6da71246c86fa2402a934632dd96e1
  lastHandledReconcileAt: "2020-10-21T04:33:31.530090319-07:00"
  lastReleaseRevision: 3
  observedGeneration: 12
```

And this Secret (:shushing_face:)

```
apiVersion: v1
data:
  cookieSecret: YW83K2tmdTBvR0RPNWFQWjQvWUQ2Y2NrR2dDbi9Sb1gyWkRwTTUyVQ==
  sharedSecret: YmJlK1BXNlBWTnd1STNYaUp1RStEUXh3eEgvVVB6ZU5QYi9WSGpTYQ==
kind: Secret
metadata:
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: sharedSecret,cookieSecret
    secret-generator.v1.mittwald.de/autogenerate-generated-at: "2020-10-21T11:21:26Z"
    secret-generator.v1.mittwald.de/secure: "yes"
    secret-generator.v1.mittwald.de/type: string
  name: pomerium-config-secrets
  namespace: pomerium
  selfLink: /api/v1/namespaces/pomerium/secrets/pomerium-config-secrets
type: Opaque
```

As you can see, the Helm chart isn't reconciling, as every attempt to do so fails with `unable to merge value from key ''sharedSecret'' in Secret ''pomerium/pomerium-config-secrets'' into target path ''config.sharedSecret'': unable to parse key: assignment to entry in nil map`.

This Secret was originally created with the data fields missing (they were created by the secret-generator operator), so I thought it might be possible that it's trying to pull its values from the empty version, but I tried restarting the Helm Controller pod and it's still happening, so I've ruled that out.
