### ISSUE TITLE
Make `spec.chart` or `spec.chartRef` required in CRD for HelmRelease

### ISSUE THREAD

**Issue by andreas-aman** [fluxcd/helm-controller#1233]
Today both `spec.chart` and `spec.chartRef` are optional.

This means that a yaml manifest such as this is correctly validated even if the dry-run will fail

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: myapp
  namespace: myapp
spec:
  timeout: 15m0s
  interval: 1m0s
```
