### ISSUE TITLE
Helm release sourced from GitRepository stuck in "not ready"

### ISSUE THREAD

**Issue by joshrwolf** [fluxcd/helm-controller#138]
Apologies if this belongs in an issue on a different repository, but I'm running into an issue when deploying a `HelmRelease` sourced from a `GitRepository`.

The `HelmRelease` is an umbrella chart containing other `HelmReleases`, minimal configuration shown below:

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: umbrella
  namespace: flux-system
spec:
  ref:
    branch: main
  url: https://<gitrepository>.git
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: umbrella
  namespace: flux-system
spec:
  chart:
    spec:
      chart: chart/
      sourceRef:
        kind: GitRepository
        name: umbrella
        namespace: flux-system
```

The basic premise of the `umbrella` chart is:

```
Chart.yaml
Chart.lock
charts/
|-- app a
     |-- Chart.yaml
     |-- templates/
|-- app b
     |-- Chart.yaml
     |-- templates/
...
```

All `dependencies` are merely locally sourced subcharts in `charts/`.

I have __successfully__ gotten it to work in several similar scenarios:

* install chart directly (`helm install umbrella -n flux-system chart/`)
* package (`helm package chart/`) and commit the .tgz, point `HelmRelease` directly to the `.tgz`
* copy the `*.tgz` from the `source-controller` pod (`/data/gitrepository/flux-system/umbrella/<cmmit sha>.tar.gz`) to my local machine and helm install pointing to the tgz

The only errors are coming from `source-controller`:

```
source-controller-6cdb6c8889-7nx76 manager {"level":"error","ts":"2020-11-03T04:38:04.135Z","logger":"controller","msg":"Reconciler error","reconcilerGroup":"source.toolkit.fluxcd.io","reconcilerKind":"HelmChart","controller":"helmchart","name":"flux-system-bigbang","namespace":"flux-system","error":"scheme \"\" not supported","errorVerbose":"scheme \"\" not supported\nhelm.sh/helm/v3/pkg/getter.Providers.ByScheme\n\t/go/pkg/mod/helm.sh/helm/v3@v3.3.4/pkg/getter/getter.go:134\ngithub.com/fluxcd/source-controller/internal/helm.NewChartRepository\n\t/workspace/internal/helm/repository.go:54\ngithub.com/fluxcd/source-controller/controllers.(*HelmChartReconciler).reconcileFromTarballArtifact\n\t/workspace/controllers/helmchart_controller.go:501\ngithub.com/fluxcd/source-controller/controllers.(*HelmChartReconciler).Reconcile\n\t/workspace/controllers/helmchart_controller.go:150\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:244\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"}
```
