### ISSUE TITLE
helm-controller Install fails, but works fine with standard Helm install

### ISSUE THREAD

**Issue by rmccright-ms3** [fluxcd/helm-controller#152]
When attempting to make a release of this [Kong Chart](https://github.com/Kong/charts/tree/main/charts/kong) the helm-controller errors out when running a _helpers template. However, this Chart installs just fine via standard Helm commands.

**The error:**
`helm-controller  Helm install failed: template: kong/templates/migrations.yaml:41:10: executing "kong/templates/migrations.yaml" at <include "kong.wait-for-postgres" .>: error calling include: template: kong/templates/_helpers.tpl: │
│ 630:6: executing "kong.wait-for-postgres" at <include "kong.no_daemon_env" .>: error calling include: template: kong/templates/_helpers.tpl:599:15: executing "kong.renderEnv" at <.>: wrong type for value; expected map[string]interface {}; got string`

**The Source/HelmRelease used:**
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: konghq
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.konghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  targetNamespace: kong
  interval: 1m
  chart:
    spec:
      #https://github.com/Kong/charts/tree/main/charts/kong
      chart: kong
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: konghq
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
```

**Comment by drewwalters96** [comment]
We're observing a similar error on a chart that we deploy successfully with the helm-operator and Helm CLI.

```
2020-11-19 15:45:02.074719 | primary | helmrelease.helm.toolkit.fluxcd.io/memcached is InProgress: reconciliation in progress
2020-11-19 15:45:02.074865 | primary | helmrelease.helm.toolkit.fluxcd.io/memcached is InProgress: Helm install failed: template: memcached/templates/deployment.yaml:55:36: executing "memcached/templates/deployment.yaml" at <include "helm-toolkit.snippets.kubernetes_entrypoint_init_container">: error calling include: template: memcached/charts/helm-toolkit/templates/snippets/_kubernetes_entrypoint_init_container.tpl:170:109: executing "helm-toolkit.snippets.kubernetes_entrypoint_init_container" at <include "helm-toolkit.snippets.kubernetes_container_security_context">: error calling include: template: memcached/charts/helm-toolkit/templates/snippets/_kubernetes_container_security_context.tpl:40:21: executing "helm-toolkit.snippets.kubernetes_container_security_context" at <$envAll.Values.pod>: can't evaluate field Values in type string
```

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    config.kubernetes.io/path: openstack/helmrelease_memcached.yaml
  name: memcached
  namespace: openstack
spec:
  chart:
    spec:
      chart: memcached
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: memcached
      version: 0.1.1
  interval: 5m
  test:
    enable: false
  timeout: 10m
  values:
    labels:
      prometheus_memcached_exporter:
        node_selector_key: kubernetes.io/os
        node_selector_value: linux
      server:
        node_selector_key: kubernetes.io/os
        node_selector_value: linux
    monitoring:
      prometheus:
        enabled: false
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  annotations:
    config.kubernetes.io/path: openstack/helmrepository_memcached.yaml
  name: memcached
  namespace: openstack
spec:
  interval: 10m
  url: https://tarballs.opendev.org/openstack/openstack-helm-infra
```

[Helper](https://opendev.org/openstack/openstack-helm-infra/src/branch/master/helm-toolkit/templates/snippets/_kubernetes_container_security_context.tpl)

[Chart](https://opendev.org/openstack/openstack-helm-infra/src/branch/master/memcached)
