### ISSUE TITLE
Helm install failed: timed out waiting for the condition

### ISSUE THREAD

**Issue by blmhemu** [fluxcd/helm-controller#174]
## Context
**HelmRelease :**

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 5m0s
```

**Helm Repository:**
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes.github.io/ingress-nginx
```

## Issue
Kubectl says that the pod is deployed and working fine. But flux says otherwise...
![image](https://user-images.githubusercontent.com/19410501/101239063-af965e00-370a-11eb-88af-469468ab5cb2.png)

Also tried increasing the interval, install retries. But nothing worked.
Also manual install with helm works just fine.
