### ISSUE TITLE
How the specify dependencies in HelmRelease?

### ISSUE THREAD

**Issue by rchrd** [fluxcd/helm-controller#203]
In Flux1 it was possible to override the dependencies of a chart like this
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chart:
    repository: my-internal-repo
    name: kube-prometheus-stack
    version: 1.2.3
    dependencies:
    - condition: kubeStateMetrics.enabled
      name: kube-state-metrics
      repository: my-internal-repo
      version: 3.2.1
```

But there is nothing about dependencies mention in de Flux2 HelmRelease CRD. Should the `repository` tag be replaced by a `sourceRef` or is this not possible in Flux2?
