### ISSUE TITLE
Multiple valuesFiles from GitRepository source

### ISSUE THREAD

**Issue by arbourd** [fluxcd/helm-controller#213]
Similar to the [create HelmRelease command in Flux](https://github.com/fluxcd/flux2/blob/24fe74f2f6cfa02cde07deb9f0aa52ddc6ce9264/cmd/flux/create_helmrelease.go#L182-L203), it would be nice if the helm-controller could handle _more than one_ values file from a single HelmChart that is sourced by a GitRepository. For example:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: example
  namespace: default
spec:
  releaseName: example
  chart:
    spec:
      chart: charts/example
      sourceRef:
        kind: GitRepository
        name: example-repo
        namespace: flux-system
      valuesFile: 
        - charts/example/values.yaml              # one
        - charts/example/values-extend.yaml       # two
        - charts/example/values-production.yaml   # three
  interval: 5m
```
