### ISSUE TITLE
Support Multiple valuesFile in HelmRelease

### ISSUE THREAD

**Issue by IronCore864** [fluxcd/helm-controller#242]
Original discussion see:

https://github.com/fluxcd/flux2/discussions/100#discussioncomment-358339

I'm creating this issue on @arbourd's behalf because it seems he didn't create this issue after the discussion.

In short, it would be nice to support passing multiple values files in the HelmRelease. Expected behaviour:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helloworld
  namespace: default
spec:
  chart:
    spec:
      chart: ./helloworld
      sourceRef:
        kind: GitRepository
        name: MyGitRepo
      valuesFile:
        - values.yaml
        - values.production.yaml
        - values.somechange.yaml
  interval: 1m0s
```

so that it will have a consistent user experience with helm.

By default, when you do `helm install xxx -f values.production.yaml`, the `values.yaml` will always be picked up first, then what's inside `values.production.yaml` will overwrite the defined values from `values.yaml`.

In fact, the first element in the valuesFile array in the example above should be omitted too but picked up anyway, just as helm does.

In fact, passing multiple values file is already supported by [flux cli](https://github.com/fluxcd/flux2/blob/24fe74f2f6cfa02cde07deb9f0aa52ddc6ce9264/cmd/flux/create_helmrelease.go#L182-L203), but not supported by using YAML, which isn't user-friendly to GitOps users.
