### ISSUE TITLE
"skipCRDs is set to false and crds is set to Skip"

### ISSUE THREAD

**Issue by ViBiOh** [fluxcd/helm-controller#260]
Hi 👋 

I've noticed what seems to be a bug. I've migrated a HelmRelease from `install.skpiCRDs` to the `install.crds` but I encounter this issue when installing from scratch.

```
"error":"Helm install failed: Contradicting CRDs installation settings, skipCRDs is set to false and crds is set to Skip"
```

My HelmRelease

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app
  namespace: default
spec:
  interval: 120m
  install:
    crds: Skip
```

If I add the `skipCRDs: true`, it's fine. Does my apiVersion wrong ?
