### ISSUE TITLE
HelmRelease Values wrongly merged when there's a TargetPath Array reference

### ISSUE THREAD

**Issue by samueltorres** [fluxcd/helm-controller#281]
Hi,
When using the `valuesFrom.targetPath` property with an array index on HelmReleases, helm-controller is not merging correctly the content of the `values <> valuesFrom` properties.

In this scenario:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
...
  values:
    prometheus:
      prometheusSpec:
        remoteWrite:
        - basicAuth:
            username:
              name: prometheus-secret
              key: username
            password:
              name: prometheus-secret
              key: password
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-secret
    valuesKey: url
    targetPath: prometheus.prometheusSpec.remoteWrite[0].url
    optional: false
```
When HelmRelease Values are merged the `remoteWrite[0].url` doesn't get merged into the `remoteWrite[0]` property.
After further investigation I've concluded that there is an issue in the composeValues function within the helm-controller.

The desired scenario would be to correctly merge the values and the url property to get the correct content.
