### ISSUE TITLE
HelmRelease with duplicate releaseName in different targetNamespaces is broken

### ISSUE THREAD

**Issue by kwening** [fluxcd/helm-controller#284]
We have an issue when there are two `HelmRelease` objects with the same `releaseName` and different `targetNamespace`.  
The first HelmRelease is bootstrapped correctly by the `helm-controller`, but when the second HelmRelease is applied to the cluster, its deployment is using the namespace of the first HelmRelease (at least for some fields).

# Environment:

Helm-Controller: `helm-controller:v0.11.1`
Flux: `flux version 0.15.2`

# Resources

**HelmRelease 1**

```yaml
kind: HelmRelease
metadata:
  name: first-flx
spec:
  releaseName: tmp
  targetNamespace: first
...
```

**HelmRelease 2**

```yaml
kind: HelmRelease
metadata:
  name: second-flx
spec:
  releaseName: tmp
  targetNamespace: second
...
```

# Result

For example, the RoleBinding in the `second` namespace looks as follows:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: tmp
    meta.helm.sh/release-namespace: first
...
subjects:
- kind: ServiceAccount
  name: default
  namespace: first
```
Here we'd expect to see the correct namespace `second` in `metadata.annotations.meta.helm.sh/release-namespace` and `subjects[0].namespace`
