### ISSUE TITLE
Not importing/parsing json values from valuesFrom correctly

### ISSUE THREAD

**Issue by philipgloot** [fluxcd/helm-controller#285]
Looking at the [example config](https://github.com/banzaicloud/banzai-charts/tree/master/thanos#example-gcs-configuration-for-object-storeyaml) this occurs when importing these values:
```
service_account: |-
    {
      "type": "service_account",
      "project_id": "project",
      "private_key_id": "abcdefghijklmnopqrstuvwxyz12345678906666",
      "private_key": "-----BEGIN PRIVATE KEY-----\...\n-----END PRIVATE KEY-----\n",
      "client_email": "project@thanos.iam.gserviceaccount.com",
      "client_id": "123456789012345678901",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/thanos%40gitpods.iam.gserviceaccount.com"
    }
```
I've tried to add these with `values` and `valuesFrom` with different kinds of secrets but still ending up on the same error.
`unable to merge value from key 'thanos.yaml' in Secret 'flux-system/thanos-objstore-secret' into target path 'objstoreConfig': key "\n      \"project_id\": \"project\"" has no value (cannot end with ,)
` when using `valuesFrom`

Also tried adding it like, `server_account: '{"type": "service_account",...}'` and similar formats both base64 encoded in a secret and not.

Everything works when installing the chart manually with helm so my theory this is flux helm-controller related.

To reproduce:
Chart: https://bitnami.com/stack/thanos/helm https://github.com/bitnami/charts/tree/master/bitnami/thanos
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: flux-system
spec:
  releaseName: thanos
  interval: 1m
  targetNamespace: core
  chart:
    spec:
      chart: charts/thanos
      sourceRef:
        kind: GitRepository
        name: x
  values:
    objstoreConfig:
      type: GCS
      config:
        bucket: x
  valuesFrom:
    - kind: Secret
      name: thanos-objstore-secret
      valuesKey: service_account
      targetPath: objstoreConfig.config
```

Tried different ways with valuesFrom, so this is just one of the ways I've tried it.
