### ISSUE TITLE
valuesFrom not merging

### ISSUE THREAD

**Issue by p3lim** [fluxcd/helm-controller#300]
I'm using the [Dex chart](https://github.com/dexidp/helm-charts/tree/master/charts/dex), where I have a base configuration and configuration for clients and connectors. Due to tooling externally to add new connectors and clients I have separated the values into both in-line and "external". These do not merge correctly.

`helm-release.yaml` file:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  chart:
    spec:
      chart: dex
      sourceRef:
        kind: HelmRepository
        name: dexidp
        namespace: flux-system
      version: 0.5.0
  interval: 1h0m0s

  valuesFrom:
    - kind: ConfigMap
      name: dex-config-connector-ldap
    - kind: ConfigMap
      name: dex-config-client-x

  values:
    config:
      issuer: https://dex.example.com
      storage:
        type: memory

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: dex.example.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: dex-tls
          hosts:
            - dex.example.com
```

`config-connector-ldap.yaml`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config-connector-ldap
  namespace: dex
data:
  values.yaml: |
    config:
      connectors:
        - type: ldap
          id: ldap
          name: ldap
          config:
            # lots of values here

    envFrom:
      - secretRef:
          name: dex-ldap-credentials
```
`config-client-x.yaml`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config-client-x
  namespace: dex
data:
  values.yaml: |
    config:
      staticClients:
        - id: foo
          name: Foo
          redirectURIs:
            - https://foo.example.com/oidc/callback
            - http://localhost:8000/oidc/callback
          secret: ...

    envFrom:
      - secretRef:
          name: dex-client-x
```

In these three files I have `config` represented three times, and this key merges just fine, however `envFrom` is represented twice and does _**not**_ merge, only one of which exists in the deployment after reconciling:

```bash
> kubectl describe -n dex pod/dex-xxxxx
...
    Environment Variables from:
      dex-client-x      Secret  Optional: false
    Environment:        <none>
...
```

**Comment by p3lim** [comment]
If I move all the `envFrom` keys and merge them myself into the in-line values they exist correctly in the deployment:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  # ...

  values:
    config:
      # ...

    envFrom:
      - secretRef:
          name: dex-ldap-credentials
      - secretRef:
          name: dex-client-x
```
Result:
```bash
> kubectl describe -n dex pod/dex-xxxxx
...
    Environment Variables from:
      dex-client-x          Secret  Optional: false
      dex-ldap-credentials  Secret  Optional: false
    Environment:            <none>
...
```

**Comment by p3lim** [comment]
It's **lists** not being merged correctly, just tested adding more clients and the `config.staticClients` key does not merge.

**Comment by kingdonb** [comment]
I think this is known. It would be nice to be able to merge lists, although it brings up some semantic questions. (I think it's fairly conventional for a list merge to append later entries after earlier ones, for example, but this might not be universal.)

For reference, this behavior you're expecting is available in Kustomize but only when the list items have a "special key" so they can be merged rather than duplicated, when they are present in both lists. That means only certain types of arrays are mergeable, in certain contexts: https://github.com/kubernetes-sigs/kustomize/issues/581#issuecomment-442415743

This behavior is specific to the Kustomize codebase though, and it's implemented by object (for example the `containers` array in a Deployment's `podSpec` are keyed by `name`.) Since values in a Helm `values` are typically untyped, that implementation cannot likely be reused and probably wouldn't be very helpful anyway.

It looks like Helm Controller just leans on the `fluxcd/pkg/runtime/transform` package, which implements MergeMaps here:

https://github.com/fluxcd/pkg/blob/main/runtime/transform/transform.go#L23

(It definitely isn't attempting to merge array members.) It just iterates through the members of the map, and if they are able to be coerced successfully into maps with string keys, it calls itself again recursively until all maps are merged throughout.

So I can tell you this behavior is expected, but as I wasn't involved in implementing this I can't say if it would be considered as a possible enhancement request. The enhancement would be something like Kustomize's special merge keys, or opt-in appending behavior depending on your preference, I guess. I'm not sure how one would handle multiple special merges in the same Helm chart... as you can see this might get pretty complicated.

If you'd like to keep this issue open, the maintainers will be coming back from vacations soon-ish, so they can weigh in.

**Comment by p3lim** [comment]
If they would like to preserve the current behavior, maybe add it as an option to `valuesFrom`? E.g.
```yaml
valuesFrom:
- kind: ConfigMap
  name: my-config-map
  mergeLists: true
```

**Comment by hiddeco** [comment]
What we are doing at present should equal the behavior of passing multiple values file to `helm` using the `-f` flag, e.g. `helm install -f a.yaml -f b.yaml`. Merging lists is, as @kingdonb has already mentioned, not a straight forward task.

If we would add a `mergeLists` flag, what would you expect to happen when this is set to `true`? Does it merge two lists (e.g. `[0, 1, 2], [2, 3, 4]`) so that it becomes `[0, 1, 2, 2, 3, 4]`, or does it become `[0, 1, 2, 3, 4]`?

**Comment by tuxillo** [comment]
Let me share what I think it might be a real scenario here.

If, for example, I have a list of `env` variables in a HelmRelease in base:

```
env:
- name: TEST
   value: true
- name: DEBUG
   value: false
```

And then a HR for a specific environment, I would expect that only the environment variables also specified in the later HR are overwritten. Anything else should just be added to the list.
