### ISSUE TITLE
Rollback: How do I use the rollback 

### ISSUE THREAD

**Issue by 51qzpw** [fluxcd/helm-controller#301]
Hi! I want to **rollback** a helmreleases.  what shoud i do?
The YAML file I defined：
``` yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-fluxcd
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: '>=2.0.0 <5.0.0'
      sourceRef:
        kind: HelmRepository
        name: helmrepository-sample
      interval: 1m
  rollback:
    cleanupOnFail: true
```
And then I excute : kubectl apply  this yaml, but I don't see any change. my helmrelease don't rollback.
Please tell me next I need to do, thank you!
