### ISSUE TITLE
Using valuesFrom causes no deployment

### ISSUE THREAD

**Issue by momania** [fluxcd/helm-controller#313]
Hi, I'm trying to make use of the `valuesFrom` feature to replace the inline values definition, but for some reason when I add this to my yaml, the deployment is not executed.
I also don't see any error log in the helm controller or anything.  The specified config map is there, in the same namespace and with a key named `values.yaml` containing the config.

I'm using:
- helm-controller:v0.11.1
- kustomize-controller:v0.13.2
- notification-controller:v0.15.0
- source-controller:v0.15.3

Is there any way I can debug this issue?

**Comment by hiddeco** [comment]
Can you please share a minimal example that creates a reproducable result; or at least share a (redacted) version of your `HelmRelease` resource and `ConfigMap`, and the output of `kubectl describe helmrelease <name>`?

This would help me understand your issue better.

**Comment by momania** [comment]
Sure thing... 

Config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-msteams
  namespace: monitoring
data:
  values.yaml: |
    connectors:
      - tech: https://etc.com
```

Helm:
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: company-prometheus-msteams
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus-msteams
      sourceRef:
        kind: HelmRepository
        name: prometheus-msteams
  interval: 1m0s
  releaseName: company-prometheus-msteams
  targetNamespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-msteams
```

Source:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-msteams
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://prometheus-msteams.github.io/prometheus-msteams/
```

`kubectl describe helmrelease <name>` gives no output... helm release is never deployed so not found.
