### ISSUE TITLE
No exponential back off on failure?

### ISSUE THREAD

**Issue by aperullo** [fluxcd/helm-controller#316]
Hello, 

It was mentioned in issue #309 that failed charts are retried on an exponential back-off.

> The interval controls the default duration between reconciles for a resource, assuming the reconcile operation did not return an error. In case of a returned error, it is retried with an exponential backoff.

I just set up the notification controller which has a default rate limit on notifications of 5 minutes. I've noticed that the channel I have it set up in though is reporting an error with a continuously failing chart every 5 minutes, instead of backing off like I would expect. 

This is the HelmRelease object in question:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio
spec:
  releaseName: minio-operator
  chart:
    spec:
      chart: minio-operator
      version: ...
      sourceRef: ...
  interval: 1m
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values: 
    ...

```

I've recreated the alerts below, note the timestamps. This particular release has been failing since around 2pm so I would expect it would have backed off to retrying to maybe like once an hour (or when I finally get around to updating the minio release to fix it) 

**helm-controller (4:10pm):**

>   helmrelease/minio-operator
>   Helm install has started

**helm-controller (4:15pm):**

>   helmrelease/minio-operator
>   Helm install failed: timed out waiting for the condition
>   beginning wait for 1 resources with timeout of 1m0s
>   creating 11 resource(s)
>   beginning wait for 11 resources with timeout of 5m0s

**helm-controller (4:15pm):**

>   helmrelease/minio-operator
>   Helm uninstall succeeded

**helm-controller (4:15pm):**

>   helmrelease/minio-operator
>   Helm install has started

**helm-controller (4:20pm):**

>   helmrelease/minio-operator
>   Helm install failed: timed out waiting for the condition
>   beginning wait for 1 resources with timeout of 1m0s
>   creating 11 resource(s)
>   beginning wait for 11 resources with timeout of 5m0s

**helm-controller (4:20pm):**

>   helmrelease/minio-operator
>   Helm uninstall succeeded

...repeat ad infinitum every 5 minutes, no back off in sight.

Is this a bug? Is that back-off capped at <5 minutes? Is it something I did? Also where in the code can I find the back-off portion.

Thank you in advance!
