### ISSUE TITLE
Helm ValuesFiles not updated during reconciliation

### ISSUE THREAD

**Issue by jonerer** [fluxcd/helm-controller#328]
Originally posted as https://github.com/fluxcd/flux/issues/3556

Thanks for a great piece of software! I'm having a blast with it.

This issue is not to report on a bug with the runtime implementation, but with the semantics of HelmRelease CRDs.

I have a HelmRelease where I load the values from normal helm value files. According to https://fluxcd.io/docs/components/helm/helmreleases/ the way to do that is to put them in the Spec, like so:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my_helm_release
  namespace: agile
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster/charts/my_helm_chart
      version: "0.1.2"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - cluster/charts/my_helm_chart/values.yaml
        - cluster/charts/my_helm_chart/values_prod_tag.yaml
```

This works perfectly file, loading in the values.yaml file and adding values_prod_tag.yaml on top. But it doesn't update the helm release on reconciliation if either of the values files are changed. Reconciliation will only pick up the changes if I bump the "version" number on the chart.

The reason why I'm using normal helm values.yaml-files instead a `ConfigMap` or `Secret` definition is twofold:

- I want to be able to use the standard helm CLI tools for debugging/development. In this case, I could do helm template my_helm_release . -f values_prod_tag.yaml to see the output and validate or so. Having my values inside a k8s resource file (like a ConfigMap or sth) would be harder
- I want to be able to easily update the values_prod_tag.yaml-file in my CI pipeline, to specify what image tag to use; updating inside a k8s resource file is trickier

Updating a values file referenced by a HelmRelease should re-render the helm chart and update the installed helm release upon reconciliation.

What I'm looking for is probably what was referred to as `valuesFrom: chartFileRef` in the Helm Operator: https://fluxcd.io/docs/migration/helm-operator-migration/#chart-file-references are there any plans to implement this for the Helm Controller? It would be awesome to be able to ship values into the rendering from a normal helm values file, rather than a `ConfigMap` or `Secret` definition file

Alternatively, if there is some other more "Flux"-y way I would be very interested to learn!

➜  ~ flux check
► checking prerequisites
✔ kubectl 1.22.0 >=1.18.0-0
✔ Kubernetes 1.20.9 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.11.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.14.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.16.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.15.4
✔ all checks passed

**Comment by jonerer** [comment]
Btw I understand that the version number needs to be changed when the chart itself changes, but not when the values are updated. It does indeed make sense that the chart itself is locked with the version number (we typically don't really bump it internally when we make a change, since we're used to a monorepo where "latest" is always the only version. But we could sort that out I guess).

**Comment by kingdonb** [comment]
The values you're referring to are really part of the chart, which is evidenced by the fact that when you set `valuesFiles` it omits the original `values.yaml` from inside of the chart.

The chart versioning covers both the template and default values, so similarly changing a file in the `values.yaml` without updating the Chart.yaml is not a valid chart update for Helm Controller. Setting `valuesFiles` overrides the default values of the chart with some other file (that must be from within the chart's directory structure, so again, like the original default values.yaml this is actually a part of the chart.)

In case it helps, you can also use the content of a configmap as the whole `values` map, to merge with the default values:

https://fluxcd.io/docs/components/helm/helmreleases/#values-overrides

If you follow the first example and leave `targetPath` unset (as in this example, from the link above):

```
  valuesFrom:
    - kind: ConfigMap
      name: prod-env-values
      valuesKey: values-prod.yaml
```

... then it's assumed the values you want to merge in are a map containing **all of the values to merge** from the configmap, `data."values-prod.yaml"` – and they come from an external Kubernetes object so they are treated as input by HelmRelease, which means that no Chart.yaml version bump is needed to trigger a release in order to enjoy them. You just have to place that configmap somewhere that it is synced by Flux at the same time as changes to your HelmRelease, so they will be picked up by Helm Controller together after any git push.

The other thing to know is that while Helm Controller subscribes to the HelmRelease for updates, there is no subscription to the ConfigMap as far as I know, so you will have to make sure if your HelmRelease is set to a long reconcile `spec.interval` that it gets reconciled in time.

This `targetPath`-less configuration might be the functionality that you're missing from Helm Operator, I think this is behaving more similar to what one could have done with `chartFileRef` in the old Helm Operator schema.
