### ISSUE TITLE
"prune: true" is ignored in Kustomizations applied by HelmRelease (regression)

### ISSUE THREAD

**Issue by artem-nefedov** [fluxcd/helm-controller#339]
### Describe the bug

After upgrading Flux  from 0.17.0 to 0.18.3, I've started observing a problem: objects installed by Kustomizations, which in turn were deployed by HelmRelease, are not deleted when Kustomization is deleted, even if `prune: true` is set (the Kustomization itself is deleted correctly).

I can also reproduce it locally with kubectl. If I deploy the following Kustomization, which creates a single namespace "foo":

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test
  namespace: default
spec:
  interval: 15m0s
  path: ./v/0.1.0/test
  prune: true
  sourceRef:
    kind: Bucket
    name: my-bucket
    namespace: flux-system
```

..and delete it like this: `kubectl delete -f test.yaml`, namespace "foo" **will not** be deleted. But, if I delete it like this: `kubectl delete ks test`, then namespace **will** be deleted. This makes me believe the issue is caused by recent changes related to server-side apply.

### Steps to reproduce

1. Create helm chart that deploys Kustomizations (Kustomizations must have `prune: true` set)
2. Deploy chart with HelmRelease
3. Delete chart
4. Validate that Kustomization is deleted (it is)
5. Validate that objects deployed by Kustomization are deleted (they're not)
  
I specifically observed the problem with Namespaces created by Kustomizations.

### Expected behavior

Everything is deleted.

### OS / Distro

N/A

### Flux version

0.18.3

### Flux check

✔ kubectl 1.21.3 >=1.18.0-0
✔ Kubernetes 1.21.2-eks-0389ca3 >=1.16.0-0
► private-repo/fluxcd/helm-controller:v0.12.0
► private-repo/fluxcd/kustomize-controller:v0.15.5
► private-repo/fluxcd/notification-controller:v0.17.1
► private-repo/fluxcd/source-controller:v0.16.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
