### ISSUE TITLE
After `ImageUpdateAutomation` bumps `subchartA.image.tag`, but `subchartB` also re-deployed on reconciliation

### ISSUE THREAD

**Issue by zzvara** [fluxcd/helm-controller#353]
### Flux version

► checking prerequisites
✗ flux 0.20.1 <0.21.0 (new version is available, please upgrade)
✔ Kubernetes 1.21.5 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.16.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.13.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.16.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.17.1
✔ all checks passed

### Kubernetes version

NAME      STATUS   ROLES                  AGE    VERSION
sigma01   Ready    control-plane,master   625d   v1.21.5
sigma02   Ready    control-plane,master   625d   v1.21.5
sigma03   Ready    <none>                 625d   v1.21.5
sigma04   Ready    <none>                 625d   v1.21.5

### `HelmRelease` in question

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testing
  namespace: development
spec:
  chart: [...]
  interval: 1m0s
  timeout: "15m"
  install:
    replace: true
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    force: true
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  values:
    frontend:
      image:
        repository: registry.example.com:443/project/front # {"$imagepolicy": "development:frontend-front:name"}
        tag: 0.15.127 # {"$imagepolicy": "development:frontend-front:tag"}
    backend:
      core:
        image:
          repository: registry.example.com:443/project/core # {"$imagepolicy": "development:backend-core:name"}
          tag: 0.15.56 # {"$imagepolicy": "development:backend-core:tag"}
```

As you can see on the above `HelmRelease`, the chart contains two sub-charts. The `backend` and the `frontend`. There are many components in the backend, but there is a `core` component that corresponds to a `Deployment` in Kubernetes.

### What happens

I can see that upon a new image available, the `ImagePolicy` is properly executed by the `ImageUpdateAutomation` and the `HelmRelease` is properly patched in the repository:

![image](https://user-images.githubusercontent.com/8371789/140085594-02ada9d8-bd80-469e-89be-153076e0c5a5.png)

As you can see, the `frontend` sub-chart's image tag is patched. In 1 minute, the frontend deployment is patched with the new image version and it restarts. **However, the backend deployment also restarts, due to unknown causes.**

### What I would expect

I would expect that only the `frontend` deployment to be restarted with the image, not the `backend`.

Why would the backend also restart? Is there anything else that is modified in the `backend` `Deployment` so that Kubernetes would restart also the `backend`?
