### ISSUE TITLE
Behaviour of the Flux when `replicas` field is not mentioned in the deployment

### ISSUE THREAD

**Issue by glen-uc** [fluxcd/helm-controller#379]
**Scenario 1:**

Create a simple deployment in a repository that is under flux control

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

Reconcile the customization and once the pod is up, scale replicas to zero by running `kubectl scale deployment -n test nginx-deployment --replicas=0`

After the deployments is scaled to zero reconcile the customization again by running `flux reconcile kustomization <name>`

Expected Result:
Flux should revert the changes made to the replicas and deployment should have `replicas=1` as mentioned in the yaml file

Actual Result:
Flux reverted the changes made to the replicas and deployment had `replicas=1`  as mentioned in the yaml file

**Scenario 2:**

Repeat the steps mentioned in Scenario 1 but this time do not specify the `replicas` field in deployment 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

Expected Result:
Flux should revert the changes made to the replicas and deployment should have `replicas=1` as mentioned in the yaml file

Actual Result:
Flux did not revert changes made to the replicas even after reconciling customization

I am not sure if this is expected behavior or an issue

```
flux: v0.24.0
helm-controller: v0.14.0
image-automation-controller: v0.18.0
image-reflector-controller: v0.14.0
kustomize-controller: v0.18.1
notification-controller: v0.19.0
source-controller: v0.19.0
```
