### ISSUE TITLE
HelmRelease valuesFiles defaulting to values.yaml 

### ISSUE THREAD

**Issue by BeardyC** [fluxcd/helm-controller#381]
When deploying a helmChart using the below HelmRelease and using ```helm-controller:v0.12.1```
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-cluster
spec:
  chart:
    spec:
      chart: redis-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta1
        kind: HelmRepository
        name: mdx-helm-snapshots
      version: 3.2.8
      valuesFile: values-dev-gcp.yaml
  install:
    crds: Skip
  interval: 1m0s
  upgrade:
    crds: Skip
  values: {}
```

I'm getting the following 

```
NAME                            CHART           VERSION   SOURCE KIND      SOURCE NAME          READY   STATUS                                      AGE
dev1-e2-dev-mdx-redis-cluster   redis-cluster   3.2.8     HelmRepository   mdx-helm-snapshots   False   failed to locate values file: values.yaml   4d2h
```

The helmchart does not have a ```values.yaml``` and I don't intend to have one in to merge values on, is a base ```values.yaml``` needed even though no merging is needed?

I've tried using a relative path - ```./values-dev-gcp.yaml``` - but no luck. Any recommendations or known issues related to this?
