### ISSUE TITLE
changing .spec.values does not reconcile release.

### ISSUE THREAD

**Issue by Lunuy** [fluxcd/helm-controller#404]
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "4.0.13"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: "192.168.0.7"
      nodePorts:
        http: 30080
        https: 30443
  reconcileStrategy: Revision
```
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "4.0.13"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
  values:
    controller: # changed
      service:
        type: LoadBalancer
        loadBalancerIP: "192.168.0.7"
        nodePorts:
          http: 30080
          https: 30443
  reconcileStrategy: Revision
```
I changed `.spec.values` field in `HelmReleaseSpec` and pushed it.

```bash
flux reconcile source git flux-system
flux reconcile helmrelease ingress-nginx -n ingress-nginx
```
I have let flux reconcile manually, but `.spec.values` of ingress-nginx release isn't changed.

```bash
kubectl describe helmrelease ingress-nginx -n ingress-nginx
```
```
Name:         ingress-nginx
Namespace:    ingress-nginx
Labels:       kustomize.toolkit.fluxcd.io/name=infrastructure
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  reconcile.fluxcd.io/requestedAt: 2022-01-24T17:30:42.3323104+09:00
API Version:  helm.toolkit.fluxcd.io/v2beta1
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2022-01-24T06:52:23Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:  2
  Managed Fields:
    API Version:  helm.toolkit.fluxcd.io/v2beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:kustomize.toolkit.fluxcd.io/name:
          f:kustomize.toolkit.fluxcd.io/namespace:
      f:spec:
        f:chart:
          f:spec:
            f:chart:
            f:sourceRef:
              f:kind:
              f:name:
              f:namespace:
            f:version:
        f:install:
          f:remediation:
            f:retries:
        f:interval:
        f:releaseName:
        f:values:
          f:service:
            .:
            f:loadBalancerIP:
            f:type:
    Manager:      kustomize-controller
    Operation:    Apply
    Time:         2022-01-24T07:03:49Z
    API Version:  helm.toolkit.fluxcd.io/v2beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizers.fluxcd.io":
    Manager:      helm-controller
    Operation:    Update
    Time:         2022-01-24T06:52:23Z
    API Version:  helm.toolkit.fluxcd.io/v2beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:reconcile.fluxcd.io/requestedAt:
    Manager:      flux.exe
    Operation:    Update
    Time:         2022-01-24T07:13:17Z
    API Version:  helm.toolkit.fluxcd.io/v2beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
        f:helmChart:
        f:lastAppliedRevision:
        f:lastAttemptedRevision:
        f:lastAttemptedValuesChecksum:
        f:lastHandledReconcileAt:
        f:lastReleaseRevision:
        f:observedGeneration:
    Manager:         helm-controller
    Operation:       Update
    Subresource:     status
    Time:            2022-01-24T07:27:11Z
  Resource Version:  54625
  UID:               422a4bed-5c87-48cc-8a43-86604a82f8dd
Spec:
  Chart:
    Spec:
      Chart:               ingress-nginx
      Reconcile Strategy:  ChartVersion
      Source Ref:
        Kind:       HelmRepository
        Name:       ingress-nginx
        Namespace:  flux-system
      Version:      4.0.13
  Install:
    Remediation:
      Retries:   3
  Interval:      1h0m0s
  Release Name:  ingress-nginx
  Values:                                               <- Here
    Service:
      Load Balancer IP:  192.168.0.7
      Type:              LoadBalancer
Status:
  Conditions:
    Last Transition Time:          2022-01-24T07:27:11Z
    Message:                       Release reconciliation succeeded
    Reason:                        ReconciliationSucceeded
    Status:                        True
    Type:                          Ready
    Last Transition Time:          2022-01-24T07:27:11Z
    Message:                       Helm install succeeded
    Reason:                        InstallSucceeded
    Status:                        True
    Type:                          Released
  Helm Chart:                      flux-system/ingress-nginx-ingress-nginx
  Last Applied Revision:           4.0.13
  Last Attempted Revision:         4.0.13
  Last Attempted Values Checksum:  b87c1161925a47c4d01e569e83d3473cb2ee7995
  Last Handled Reconcile At:       2022-01-24T17:30:42.3323104+09:00
  Last Release Revision:           1
  Observed Generation:             2
Events:                            <none>
```
Is this bug or intended function? How can I let them update `HelmRelease` object when I change `.spec.values`?
