### ISSUE TITLE
Ability to use git path as values.yaml source

### ISSUE THREAD

**Issue by corinz** [fluxcd/helm-controller#424]
@the-fine @squaremo @kingdonb  Had discussed prior on an old issue that is still relevant: [Support values files for helm](https://github.com/fluxcd/flux/issues/1349)

The link between my Flux HelmRelease and my Helm Chart is a GitRepository that has a path to the Chart.yaml. If I cannot include the path to values.yaml as well, I am forced to specify them statically from the command line for injection into my Flux HelmRelease. This is possible but creates static values hardcoded to the Flux HelmRelease. My chart will be GitOps enabled, but my values will not and will need to be adjusted in separate modifications to the HelmRelease. The Helm values would exist in two places, and there would be a separate workflows for developing directly with Helm. Not to mention the capability for full GitOps is gone.

Can you help? This is a make or break for me unfortunately. Do you have any other suggestions?

I would appreciate any feedback! Thank you!

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./ala-monitoring
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 5s
  targetNamespace: monitoring
# Hard-coding values here is an odd quirk in an otherwise seamless workflow
  values:
    grafana:
      enabled: true
```

Proposed:
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
spec:
  chart:
    spec:
      chart: ./ala-monitoring
      values: ./ala-monitoring/values.yaml # <-- PROPOSED FEATURE
      sourceRef:
        kind: GitRepository
        name: flux-system
...
```
