### ISSUE TITLE
helm-controller does not accept if code that helm did and throws already defined error

### ISSUE THREAD

**Issue by jprecuch** [fluxcd/helm-controller#427]
We've been using until now little messy but code that worked nicely with helm (--dry-run or upgrade/install)

Example of not-accepted code:
``` 
apiVersion: v1
kind: ConfigMap
metadata:
  name: nfsaas-configmap
  namespace: {{ .Release.Namespace }}
data:
  sdeVersion: "0.0.0"
  logLevel: "{{ .Values.dev.logLevel }}"
  zapiLogLevel: "{{ .Values.dev.zapiLogLevel }}"
  logSQL: "{{ .Values.dev.logSQL }}"
{{- if eq .Values.global.hyperscaler "azure" }}
  sdeVersion: "2.0.0"
  logLevel: "{{ .Values.azure.logLevel }}"
  zapiLogLevel: "{{ .Values.azure.zapiLogLevel }}"
  logSQL: "{{ .Values.azure.logSQL }}"
{{- else if eq .Values.global.hyperscaler "gcp" }}
  sdeVersion: "1.0.0"
  logLevel: "{{ .Values.gcp.logLevel }}"
  zapiLogLevel: "{{ .Values.gcp.zapiLogLevel }}"
  logSQL: "{{ .Values.gcp.logSQL }}"
{{- else if eq .Values.global.hyperscaler "aws" }}
  sdeVersion: "3.0.0"
  logLevel: "{{ .Values.aws.logLevel }}"
  zapiLogLevel: "{{ .Values.aws.zapiLogLevel }}"
  logSQL: "{{ .Values.aws.logSQL }}"
{{- end }}

Yes looking at this it seems there will be doubled values if we specify one of hyperscaler which is in if code.
However this was properly accepted by helm and always "hyperscaler if code" took over.
helm-controller however does not like this and will end with doubled values
```
{"level":"error","ts":"2022-02-28T15:07:23.262Z","logger":"controller.helmrelease","msg":"Reconciler error","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"sde","namespace":"sde","error":"Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:\n  line 16: mapping key \"sdeVersion\" already defined at line 11\n  line 17: mapping key \"logLevel\" already defined at line 12\n  line 18: mapping key \"zapiLogLevel\" already defined at line 13\n  line 19: mapping key \"logSQL\" already defined at line 14"}
```

Is there some easy fix for this or just adjust our helmchart to proper way? Thanks
