### ISSUE TITLE
[Question] How helm controller handles releases with long graceful termination period

### ISSUE THREAD

**Issue by glen-uc** [fluxcd/helm-controller#428]
Consider this scenario

We have a helm release for a deployment for which `terminationGracePeriodSeconds` is set at `3600s` and it takes full `3600s`  to gracefully terminate and it has `Recreate` as strategy

For the helm release, let's say timeout is `2h` and helm controller concurrency is set to `1`

Now when we reconcile that particular helm release it will take at least  `3600s` for it to reconcile successfully (i.e for the Ready status to be True) as old pods need to terminate and new pods need to be ready

During this period if we try to reconcile some other release will the helm controller be able to reconcile it or will it be stuck since it's already handling the above helm release?

The reason for the question is we had a scenario somewhat similar to the above and when we tried to reconcile the helm release we got this error

```
✔ HelmRelease annotated
◎ waiting for HelmRelease reconciliation
✗ context deadline exceeded
```

**Comment by stefanprodan** [comment]
By default all Flux controllers have 4 workers, for helm-controller this means it can reconcile 4 releases in parallel. See here how to increase the number of workers: https://fluxcd.io/docs/cheatsheets/bootstrap/#increase-the-number-of-workers

**Comment by cep21** [comment]
Can you help describe which of the three deployments need each parameter?  Or do the parameters work for all deployments?

```
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=20
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kube-api-qps=500
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kube-api-burst=1000
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-dependency=5s      
    target:
      kind: Deployment
      name: "(kustomize-controller|helm-controller|source-controller)"
```
