### ISSUE TITLE
Does ValuesFrom support secret in gzip format

### ISSUE THREAD

**Issue by zerunhu** [fluxcd/helm-controller#448]
Sometimes because the data of the secret is too large, it will use gzip for compression. Does the ValuesFrom of helm-controller support obtaining the data of the gzip type? For example, you can judge this Annotations: encoding: gzip . If it is yes, then you can The data is decompressed, and then the value is obtained according to its key.

My case:
I create my infrastructure through terrafrom, and set its backend to k8s, then the state of its backend is stored through secret, because the data of the state may be too large, so it is compressed by a gzip, and I create it through terraform The load-balance needs to get the load-balance-id to fill in helm's service.yaml, so I assign values through ValuesFrom, so I need to get this value from a gzip secret.

If this feature is not available, I'd be happy to submit a PR

this is secret:
![image](https://user-images.githubusercontent.com/44351924/160066567-2dba225c-dadb-4406-9d8c-2eadb975393f.png)

This is how I get his data through kubctl:
![image](https://user-images.githubusercontent.com/44351924/160067609-53635492-6fe7-447b-9b9a-451257ab3975.png)

This is a normal secret:
![image](https://user-images.githubusercontent.com/44351924/160067840-e499dc02-2679-49d4-9f34-177265dec8be.png)

**Comment by hiddeco** [comment]
This is not something we support.

I also do not think that we are open to supporting it as proposed, as the `encoding: gzip` annotation is a Terraform specific annotation and not conform Kubernetes standards, for which a [custom Secret Type](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types) would have been more fitting.

This is for example done by Helm, which also stores releases in a compressed format:

```yaml
Name:         sh.helm.release.v1.podinfo-1648201816.v1
Namespace:    source-system
Labels:       modifiedAt=1648201817
              name=podinfo-1648201816
              owner=helm
              status=deployed
              version=1
Annotations:  <none>

Type:  helm.sh/release.v1

Data
====
release:  28176 bytes
```
