### ISSUE TITLE
Discussion: Action trigger APIs

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/helm-controller#5]
The OnCondition fields currently in #2 seem error prone as there are many non-sensical condition states to use as triggers for certain actions e.g.:

* install failure triggering a rollback
* test failure (even after install) triggering a rollback
* install/upgrade/test *success* triggering an uninstall/rollback.
* reconciliation success/failure triggering anything

To stoke discussion, here is a sketch of an API for specifying triggers for actions which I think matches use cases more closely, with default values shown:

```yaml
spec:
  install:
    # remediation strategy for install is always uninstall
    maxRetries: 5 # each retry implies remediation
    remediateLastRetry: false # set to false to leave last retry in place for debugging purposes
  upgrade:
    remediationStrategy: rollback # uninstall also supported
    maxRetries: 0
    remediateLastRetry: false
  test:
    enable: true
    interval: null
    # takes into account preceding install / upgrade remediation config
    remediateFailures: true 
    remediateDelayedFailures: false # failures due to interval or e.g. `helm.fluxcd.io/testAt` annotation
  rollback: # how, not when
    timeout: 300
  uninstall: # how, not when
    timeout: 300
```
