### ISSUE TITLE
Chart pull error "oci://public.ecr.aws"

### ISSUE THREAD

**Issue by michaelsatish** [fluxcd/helm-controller#510]
Hi,

I am trying to have flux manage ack eks controller helm chart and ran into a "chart pull" error. It could be my helm release configuration. Any help will be much appreciated.

**Helm Repository**
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ack-eks
  namespace: ack-system
spec:
  interval: 1m0s
  url: oci://public.ecr.aws/aws-controllers-k8s
  type: "oci"
  secretRef:
    name: ecr-credentials
```

```sh
❯ k get helmrepository -n ack-system
NAME      URL                                        AGE   READY   STATUS
ack-eks   oci://public.ecr.aws/aws-controllers-k8s   77m   True    Helm repository is ready
```

**Helm Release**
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ack-eks
  namespace: ack-system
spec:
  chart:
    spec:
      chart: eks-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ack-eks
      version: v0.1.3
  interval: 1m0s
  values:
    serviceAccount: 
      name: ack-eks-sa
    aws:
      region: us-east-1
```

```sh
❯ k get helmchart -n ack-system
NAME                 CHART       VERSION   SOURCE KIND      SOURCE NAME   AGE   READY   STATUS
ack-system-ack-eks   eks-chart   v0.1.3    HelmRepository   ack-eks       67m   False   chart pull error: chart pull error: failed to get chart version for remote reference: unable to locate any tags in provided repository: oci://public.ecr.aws/aws-controllers-k8s/eks-chart
```

Deploying it manually works,

```sh
helm install ack-eks-controller oci://public.ecr.aws/aws-controllers-k8s/eks-chart --version=v0.1.3 --set=aws.region=us-east-1 -n ack-system
```
