### ISSUE TITLE
helm dependency update

### ISSUE THREAD

**Issue by jfcoz** [fluxcd/helm-controller#535]
Is there a way to configure a HelmRelease to do a `helm dependency update` ?

For example, I’m using kube-prometheus-stack from a HelmRepository.

https://github.com/prometheus-community/helm-charts/blob/cc3507f45176a44dda9669d1818013f9a016738e/charts/kube-prometheus-stack/Chart.yaml#L41-L53 :
```
dependencies:
  - name: kube-state-metrics
    version: "4.18.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "4.2.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: nodeExporter.enabled
  - name: grafana
    version: "6.38.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
```

How can I auto update grafana to last 6.38.* ?
