### ISSUE TITLE
Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors

### ISSUE THREAD

**Issue by cwrau** [fluxcd/helm-controller#558]
The following resource produces the following error;

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: base-cluster
  namespace: flux-system
spec:
  chart:
    spec:
      chart: base-cluster
      sourceRef:
        kind: HelmRepository
        name: teuto-net
        namespace: flux-system
      version: x.x.x
  interval: 1m
  values:
    dns:
      email: cwr@teuto.net
    global:
      baseDomain: cwrau.wtf
      clusterName: test
      helmRepositories:
        cilium:
          url: https://helm.cilium.io/
        falco:
          url: https://falcosecurity.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: teuto-net
  namespace: flux-system
spec:
  url: https://teutonet.github.io/teutonet-helm-charts
```

```
HelmRelease reconciliation failed: Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 21: mapping key "apiVersion" already defined at line 2
  line 22: mapping key "kind" already defined at line 3
  line 23: mapping key "metadata" already defined at line 4
```

And I can't for the life of me figure out why.

`yq` parses successfully, `helm upgrade` works, manually looking over the `helm template` yaml looks ok

Especially since a duplicate `apiVersion` would definitely trigger errors in other tools as well
