### ISSUE TITLE
How to use a values.yaml without ConfigMap or Secret?

### ISSUE THREAD

**Issue by kespineira** [fluxcd/helm-controller#586]
Hello everyone, I am trying to use a values.yaml in a HelmRelease that is neither in the chart nor do I want to configure it as ConfigMap or Secret. Is there any possibility to apply it?

To clarify a bit what I have. Repo structure:
└── flux-system
│   ├── kustomization.yaml
│   ├── gotk-sync.yaml
│   ├── gotk-components.yaml
│   ├── jenkins.yaml
│   └── jenkins-values.yaml

gotk-sync.yaml
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: <REPO_URL>
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

jenkins.yaml
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jenkins
spec:
  interval: 1m0s
  url: https://charts.jenkins.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
spec:
  chart:
    spec:
      chart: jenkins
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jenkins
      version: 4.2.17
  interval: 1m0s
```
