### ISSUE TITLE
feature: Syncing helmrelease from gitrepository and helmrepo

### ISSUE THREAD

**Issue by NissesSenap** [fluxcd/helm-controller#591]
Today I have a meta helm chart that contains multiple private helm charts as dependencies. These charts have all been pushed to an private OCI registry.

In my QA environment I want to verify that my meta helm chart is working as intended before creating a new release.
So in short I wanted my helm chart to be synced from my git repository while having dependencies that is located in a OCI repositroy.

This is how my Chart.yaml looks like in my meta helm chart:

```
apiVersion: v2
name: meta-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.10
appVersion: "1.16.0"

dependencies:
  - name: auth-api
    version: 0.1.7
    repository: oci://soprivate.azurecr.io/helm
```

I have tried the following:

``` 
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: helm
spec:
  gitImplementation: libgit2
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: helm-git-pat
  timeout: 20s
  url: https://dev.azure.com/myOrg/myProject/_git/helm-charts
```

```.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: meta-chart
spec:
  interval: 5m
  releaseName: meta-chart
  serviceAccountName: flux
  chart:
    spec:
      chart: ./meta-chart
      version: 0.1.11
      sourceRef:
        kind: GitRepository
        name: helm
  values:
    oci-chart1:
      foo: bar
```

Looking at the helmcharts that gets generated it gives me the following:

```shell
$ k describe helmcharts.source.toolkit.fluxcd.io meta-chart
....
Events:
  Type     Reason                Age                  From               Message
  ----     ------                ----                 ----               -------
  Warning  DependencyBuildError  51m (x4 over 77m)    source-controller  dependency build error: failed to add remote dependency 'auth-api': chart download of version '0.1.7' failed: failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
 ``` 

This isn't strange since I don't have any helmrepositories configuration.
But I can't do that since the `helmreleases.helm.toolkit.fluxcd.io` CRD just take an object and not a list of objects:
`k explain helmreleases.helm.toolkit.fluxcd.io.spec.chart.spec.sourceRef`.

I don't have a good suggestion how to solve this, I understand changing this CRD isn't something that you want to do but I think it would be nice if this use case would be supported.
