### ISSUE TITLE
reconcilation too long time

### ISSUE THREAD

**Issue by perrornet** [fluxcd/helm-controller#605]
This problem occurs frequently and causes a 10-minute delay in updates.
Loging:
```
│ {"level":"info","ts":"2023-02-10T09:39:12.423Z","msg":"reconcilation finished in 22.74420191s, next run in 1m0s","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name
```
version: v0.26.0
Deployment patches yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-controller
  template:
    spec:
      containers:
        - name: manager
          resources:
            limits:
              cpu: 6000m
              memory: 4Gi
            requests:
              cpu: 4000m
              memory: 64Mi
```
Args patches yaml:
```
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: helm-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kube-api-qps=100
```
CPU memory usage:
<img width="1599" alt="image" src="https://user-images.githubusercontent.com/23651751/218060515-e51bb381-305b-4226-919d-c1339f224f6f.png">
