### ISSUE TITLE
Service account token gets recreated over and over

### ISSUE THREAD

**Issue by tachang** [fluxcd/helm-controller#608]
Each time flux deploys the helm chart I seem to be getting a new service-account-token being recreated. I've tried searching for "service account", "token" in the issues but don't see much popping up. I did see this PR on a separate project: https://github.com/Kong/charts/issues/30 that seems kinda what I am experiencing.

Is this the result of using both a kustomize-controller and helm-controller (which I am)?

Not sure if there is any documentation or bug report around this issue.

```
$ flux version
flux: v0.37.0
helm-controller: v0.27.0
kustomize-controller: v0.31.0
notification-controller: v0.29.0
source-controller: v0.32.1
```

`kubectl get secrets`

```
NAME                                     TYPE                                  DATA   AGE
default-token-f2g56                      kubernetes.io/service-account-token   3      62d
example-token-257sw               kubernetes.io/service-account-token   3      35d
example-token-28q7s               kubernetes.io/service-account-token   3      35d
example-token-29bfb               kubernetes.io/service-account-token   3      10d
example-token-2b9sv               kubernetes.io/service-account-token   3      28d
example-token-2bmfd               kubernetes.io/service-account-token   3      18d
```

**Comment by stefanprodan** [comment]
Flux does not create service account tokens, this is a feature in Kubernetes. I guess you've explicitly enable the token creation in your chart and what you observe is Kubernetes rotating the token when it expires, docs https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#tokenrequest-api

**Comment by tachang** [comment]
The chart I am trying to release inherits or sources from a base chart (does that make sense?).

Inside a components.yaml I have:

```
{{ include "base.namespace" $ }}
{{ include "base.serviceaccount" $ }}
{{ include "base.deployment" $ }}
{{ include "base.virtualservices" $ }}
{{ include "base.services" $ }}
```

I assume the interesting one is the serviceaccount piece.

```
{{- define "base.serviceaccount" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base.meta.servicename" $ }}
  {{- with (and .Values.serviceAccount .Values.serviceAccount.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
  - name: reciprocity-k8s-deployment-pull-secret
{{- end }}
```


This creates the service account:
```
apiVersion: v1
imagePullSecrets:
- name: k8s-deployment-pull-secret
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: example-dev
    meta.helm.sh/release-namespace: example-dev
  creationTimestamp: "2022-11-23T19:29:49Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: example-dev
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: example-dev
  namespace: example-dev
  resourceVersion: "632835693"
  uid: 3bf9ef59-587f-474a-bdd5-560d6b6aeeec
secrets:
- name: example-dev-token-khp2n
```

This is what the HelmRelease looks like:


```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: example-dev
  namespace: flux-system
spec:
  releaseName: example-dev
  targetNamespace: example-dev
  interval: 10m0s
  chart:
    spec:
      chart: ./charts/example/dev
      version: "0.0.1-dev"
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-manifests
      valuesFiles:
        - ./charts/example/values.yaml
        - ./charts/example/dev/values.yaml
  upgrade:
    disableWaitForJobs: false
    force: true
  install:
    disableWaitForJobs: false
---
```

So what I am seeing is that everytime I push a new change to the github repo things do reconcile and work but I keep getting secrets being created. I only have one serviceaccount and the ages is like 50days old.
