### ISSUE TITLE
Cannot use OCIRepository (no Helm Repository on OCI!)

### ISSUE THREAD

**Issue by dex4er** [fluxcd/helm-controller#616]
I use Helm charts from Git repository like:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
spec:
  chart:
    spec:
      chart: ./infrastructure/app/helm
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
```

I don't see any option to use it here an OCIRepository instead. I'm not quite sure if using HelmRepository with `url: oci://` is a good alternative: I have a single artifact for a whole tree and I would like to avoid using multiple `sourceRef`s and multiple `flux push` commands if possible.
