### ISSUE TITLE
Helm upgrade failed with values from k8s secret

### ISSUE THREAD

**Issue by Sebor** [fluxcd/helm-controller#667]
I have an encrypted (by sops) values.yaml and bitnami postgres-ha chart (v10.0.7). As I understand I cannot decrypt this file directly that's why I use `valuesFrom` option.
The installation looks good, but when I change any helm value I get the error:
```
Helm upgrade failed: execution error at (postgresql-ha/templates/NOTES.txt:101:4):
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'postgresql.password' must not be empty, please add '--set postgresql.password=$PASSWORD' to the command. To get the current value:

        export PASSWORD=$(kubectl get secret --namespace "infra" postgres-ha-postgresql-ha-postgresql -o jsonpath="{.data.password}" | base64 -d)

    'postgresql.repmgrPassword' must not be empty, please add '--set postgresql.repmgrPassword=$REPMGR_PASSWORD' to the command. To get the current value:

        export REPMGR_PASSWORD=$(kubectl get secret --namespace "infra" postgres-ha-postgresql-ha-postgresql -o jsonpath="{.data.repmgr-password}" | base64 -d)

    'pgpool.adminPassword' must not be empty, please add '--set pgpool.adminPassword=$ADMIN_PASSWORD' to the command. To get the current value:

        export ADMIN_PASSWORD=$(kubectl get secret --namespace "infra" postgres-ha-postgresql-ha-pgpool -o jsonpath="{.data.admin-password}" | base64 -d)
```
It seems like values from the secret are ignored.

How to reproduce.

Helmrelease manifest:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-ha
  namespace: flux-system
spec:
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: charts/infra/postgres-ha/postgresql-ha-bitnami
      sourceRef:
        kind: GitRepository
        name: charts-repo
      reconcileStrategy: Revision
      valuesFiles:
        - charts/infra/postgres-ha/postgresql-ha-bitnami/values.yaml
        - charts/infra/postgres-ha/postgresql-ha-bitnami/values-dev.yaml
  valuesFrom:
    - kind: Secret
      name: postgres-secrets-77kdc9gmd4
  interval: 10m
  dependsOn:
    - name: ingress-nginx
  install:
    createNamespace: true
  releaseName: postgres-ha
  targetNamespace: infra
```

Kustomization manifest (to decrypt secret values and put them into the k8s secret)
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sops-postgres-ha
  namespace: flux-system
spec:
  path: charts/infra/postgres-ha/postgresql-ha-bitnami
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: charts-repo
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  prune: true
```

kustomization.yaml (inside chart directory):
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: postgres-secrets
    namespace: flux-system
    files:
      - values.yaml=secrets-dev.yaml
    # options:
    #   disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
```

kustomizationconfig.yaml (inside chart directory):
```
nameReference:
  - kind: Secret
    version: v1
    fieldSpecs:
      - path: spec/valuesFrom/name
        kind: HelmRelease
```

The data of postgres-secrets-77kdc9gmd4:
```
global:
    postgresql:
        password: postgrespassword
        repmgrPassword: repmgrpassword
    pgpool:
        adminPassword: pgpoolpassword
pgpool:
    customUsers:
        usernames: user1
        passwords: password1
```

values-dev.yaml:
```
pgpool:
  replicaCount: 2
postgresql:
  replicaCount: 3
```

After hr installation change, for example, pgpool.replicaCount to 1 you will get the error above.

Any idea what I'm doing wrong?
