### ISSUE TITLE
OCI type HelmRepository fails to pull Chart version

### ISSUE THREAD

**Issue by dmelenteanu-quorum** [fluxcd/helm-controller#670]
I am trying to install Karpenter via a HelmRelease, but the HelmChart is not able to become ready, failing with `chart pull error: failed to get chart version for remote reference: could not get tags for "karpenter": unable to locate any tags in provided repository: oci://public.ecr.aws/karpenter/karpenter`

I can pull the specific version of the chart and can instal it via Helm.
I understand the public.ecr.aws repo does not publish tags, but I am pinning the version to something very specific. I believe there should be a way to pull the Chart version without having to do a tag list.

```
flux version
flux: v0.39.0
helm-controller: v0.28.1
kustomize-controller: v0.32.0
notification-controller: v0.30.2
source-controller: v0.33.0
```

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: karpenter
  namespace: flux-system
spec:
  interval: 30s
  type: oci
  url: oci://public.ecr.aws/karpenter
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: karpenter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: karpenter
      version: =v0.27.1
  values:
     ..........
```
