### ISSUE TITLE
HelmRelease values not rolled back when upgrade fails

### ISSUE THREAD

**Issue by PeterFras** [fluxcd/helm-controller#689]
Hi all,

Helm Controller version: **0.33.0**
Similar issue: https://github.com/fluxcd/helm-operator/issues/513
k8s version: 1.24.11

I have a very simple chart which deploys a test job. The job will echo `TEST` and exit with `EXIT` exit code.

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
  annotations:
    helm.sh/hook: test
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: busybox:1.36.0
        name: load-test
        command: ["/bin/sh", "-c"]
        args:
          - echo $TEST;
            exit $EXIT;
        resources:
          requests:
            cpu: 1
            memory: 200Mi
          limits:
            memory: 1Gi
            cpu: 2
        env:
          - name: TEST
            value: {{ .Values.env.test }}
          - name: EXIT
            value: {{ quote .Values.env.exit }}
```

By default, the job will echo `FROM_FILE` and exit with `0`:
```yaml
env:
  test: FROM_FILE
  exit: 0
```

Associated HelmRelease:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test
  namespace: test
spec:
  interval: 1m
  chart:
    spec:
      chart: test
      version: test
      sourceRef:
        kind: HelmRepository
        name: test
  test:
    enable: true
  upgrade:
    remediation:
      retries: 1
      strategy: rollback
  values:
    env:
      test: FROM_HELM_RELEASE
```

The chart is installed fine, the job echoes `FROM_HELM_RELEASE` and finishes successfully:
```yaml
status:
  conditions:
  - lastTransitionTime: "2023-05-19T10:25:28Z"
    message: Release reconciliation succeeded
    reason: ReconciliationSucceeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-05-19T10:25:24Z"
    message: Helm install succeeded
    reason: InstallSucceeded
    status: "True"
    type: Released
  - lastTransitionTime: "2023-05-19T10:25:28Z"
    message: Helm test succeeded
    reason: TestSucceeded
    status: "True"
    type: TestSuccess
```

Now, I am simulating a test failure by changing exit code to `1` in HelmRelease:
```yaml
values:
  env:
    test: FROM_HELM_RELEASE
    exit: 1
```

The job fails with exit code `1` and rollback is initiated:
```yaml
status:
  conditions:
  - lastTransitionTime: "2023-05-19T10:28:50Z"
    message: "Helm test failed: 1 error occurred:\n\t* job failed: BackoffLimitExceeded\n\n"
    reason: TestFailed
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-05-19T10:28:50Z"
    message: "Helm test failed: 1 error occurred:\n\t* job failed: BackoffLimitExceeded\n\n\n\nLast
      Helm logs:\n\n"
    reason: TestFailed
    status: "False"
    type: Released
  - lastTransitionTime: "2023-05-19T10:28:50Z"
    message: "Helm test failed: 1 error occurred:\n\t* job failed: BackoffLimitExceeded\n\n\n\nLast
      Helm logs:\n\n"
    reason: TestFailed
    status: "False"
    type: TestSuccess
  - lastTransitionTime: "2023-05-19T10:28:50Z"
    message: Helm rollback succeeded
    reason: RollbackSucceeded
    status: "True"
    type: Remediated
  failures: 1
```

To my surprise, after rollback, HelmRelease values remained unchanged (exit code is still 1). I would expect HelmRelease values to be also rolled back:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: "2023-05-19T10:25:22Z"
  finalizers:
    - finalizers.fluxcd.io
  generation: 2
  name: test
  namespace: test
spec:
  chart:
    spec:
      chart: test
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: test
      version: test
  interval: 1m
  test:
    enable: true
  upgrade:
    remediation:
      retries: 1
      strategy: rollback
  values:
    env:
      exit: 1
      test: FROM_HELM_RELEASE
```
