### ISSUE TITLE
Spread many HelmRelease updates / What is the interval doing?

### ISSUE THREAD

**Issue by flixx** [fluxcd/helm-controller#700]
Hello!

**In our cluster we are having the following situation:**
We have a lot of similar namespaces with flux-managed identical helm charts deployed in it.
This is how we do multi-tenancy for our customers. Both our `HelmRelease` Resource and the helm chart lives in a `GitRepositories`. We are using `ImageRepository` as well as one centralized `ImageUpdateAutomation` resource to change tags in the `HelmRelease` whenever there is a new Image available.

Our HelmRelease resources look like this:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: our-app
  namespace: customer26
spec:
  interval: 60m
  timeout: 12m
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: customer26-our-app
        namespace: flux-system
      valuesFiles:
        - "values.yaml"
        - "values-prod.yaml"
      reconcileStrategy: Revision
  upgrade:
    remediation:
      retries: -1
  install:
    remediation:
      retries: -1
  values:
     ...
```
The helm-controller is on `v0.29.0`

**Now the problem is:**
Whenever we update the application, all releases in all namespaces will update simultaneously. First the `ImageUpdateAutomation` kicks in to update all tags. Then the source-controller updates all `HelmReleases`. Then the `helm-controller` updates all Helm Releases simultaneously. The update process is a bit resource-intense (rolling upgrades + init jobs). Since all updates of all environment happen at the same time, our cluster is quite under stress for every update.

**The idea:**
So, our idea was to spread the helm updates a bit in time. So that not all helm updates happen simultaneously but a bit randomised  e.g. within a 30min window.

**What we've tried:**
Initially we thought this is easily solvable by increasing the `interval` in the HelmRelease resource to `60m`. However this does not seem to work. The helm-controller will update the adjustments to the helm release immediately after editing the `HelmRelease` resource. Here my ask would be to clarify what the `interval` actually is intended for, if changes on the `HelmRelease` are being watched by the controller anyway?

Is it somehow possible to make the helm-controller not watch for changes in the `HelmRelease` resource and make applies right away but instead wait for the new reconciliation run?

Thanks!
