### ISSUE TITLE
Helm release unable to rollback manual changes after enabling drift detection

### ISSUE THREAD

**Issue by sojinss4u** [fluxcd/helm-controller#742]
Hello,

I am currently using flux version 'v0.41.2' (Helm Controller Version: v0.31.2). I have enabled '--feature-gates=DetectDrift=true' in Helm controller so that the manual changes in helm deployments can be automatically rolled back. After enabling this feature I have seen the following error in our Kyverno helm release.

```
$ flux get hr | grep -i kyverno                                                               

kyverno                         2.5.5+2dbac08dfae2.2    False           False   failed to diff release against cluster resources: Deployment/ky
verno/kyverno-kyverno dry-run failed, reason: Invalid, error: Deployment.apps "kyverno-kyverno" is invalid: spec.template.spec.containers[0].re
sources.requests: Invalid value: "500Mi": must be less than or equal to memory limit
```

In the HelmChart the value for kyverno deployment memory limit is 200Mi & request is 100Mi. I have manually edited the deployment inside the cluster & increased request to 500Mi & limit to 1000Mi. After the changes helm is unable to automatically revert the changes & showing above error. I believe this error is coming as the actual memory request value present in the cluster (500Mi) > the memory limit present in the HelmChart. If I make the request less than 200Mi in the cluster, the error disappears & rollback automatically happen. However this is a problem as now these manual changes can't be reverted by Helm drift detection. Is there any solution to this problem?
cc: @hiddeco

**Comment by sojinss4u** [comment]
This issue is resolved after setting "spec.upgrade.disableOpenAPIValidation: true". Do you see any downside of disabling openapi validation?

**Comment by somtochiama** [comment]
I am trying to reproduce this @sojinss4u .
I have installed the kyverno helm chart  with the following manifest
```
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  targetNamespace: kyverno
  releaseName: kyverno
  interval: 30m
  install:
    createNamespace: true
  chart:
    spec:
      chart: kyverno
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 30m
```

Then edited the `kyverno` deployment in cluster to use limits: 1000Mi and request 500Mi
```
Deployment/kyverno/kyverno diff:
.metadata.generation
-2
+3

.spec.template.spec.containers[0].resources.limits.memory
-1000Mi
+384Mi

.spec.template.spec.containers[0].resources.requests.memory
-500Mi
+128Mi
```

Is there any steps I might be missing?
Pretty weird that the value on the cluster is causing an error during dry run since the manifest used for the dry run is gotten from the prev release
