### ISSUE TITLE
helmrelease values still present after deleting

### ISSUE THREAD

**Issue by echCRW** [fluxcd/helm-controller#771]
certain keys in helmrelease wont be updated when reapplying the manifest.
here is an example of this issue:
```yml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
...
  values:
    installCRDs: true
    resources:
      limits:
        memory: 90Mi
      requests:
        cpu: 15m
        memory: 40Mi
    webhook:
      resources:
        limits:
          memory: 25Mi
        requests:
          cpu: 5m
          memory: 10Mi
    cainjector:
      resources:
        limits:
          memory: 125Mi
        requests:
          cpu: 14m
          memory: 105Mi
```

This is the original manifest file which was applied by flux.
After that, we suspended the kustomization and a manual kubectl apply with the following file:

```yml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
...
  values:
    installCRDs: true
```

we expected the values section to now only contain the key `installCRDs`  but instead found out the applied kubernetes manifest still contained the `cainjector` & `webhook` keys.

After deleting the helmrelease and reapplying it, the values section was correct.

**Comment by hiddeco** [comment]
Without more context, it is hard to be of any help.

**Comment by echCRW** [comment]
@hiddeco Sorry, turns out by pressing enter without focusing the textfield first an issue gets created without any content.
I updated the comment.

**Comment by hiddeco** [comment]
> we expected the values section to now only contain the key `installCRDs`

With "values section", do you mean the `.spec.values` as retrieved from `kubectl get helmrelease -o yaml ...`, or the values as reflected by `helm get values ...`?

**Comment by echCRW** [comment]
@hiddeco Yes, i mean the `.spec.values` from `kubectl describe helmrelease ...`

**Comment by echCRW** [comment]
We just found out this only happens if the helmrelease was previously applied by flux. 
It does not happen if the helmrelease gets manually applied while the flux kustomization is suspended.

**Comment by hiddeco** [comment]
This means it is not an issue of the helm-controller, but rather has to do something with the apply (as the controller only looks at the current state as presented by the Kubernetes API). Making it a kustomize-controller or `kubectl` apply issue, and I suspect it being related to e.g. field managers being set.

**Comment by stefanprodan** [comment]
> It does not happen if the helmrelease gets manually applied while the flux kustomization is suspended.

This is how Flux was designed to work, any kubectl edits are promptly reverted. See the FAQ here https://fluxcd.io/flux/faq/#why-are-kubectl-edits-rolled-back-by-flux

**Comment by ndrscodes** [comment]
> > It does not happen if the helmrelease gets manually applied while the flux kustomization is suspended.
> 
> 
> 
> This is how Flux was designed to work, any kubectl edits are promptly reverted. See the FAQ here https://fluxcd.io/flux/faq/#why-are-kubectl-edits-rolled-back-by-flux

@stefanprodan does this rollback happen if the root kustomization is suspended?

I also believe the issue is caused by some kubectl bug, so this issue should probably be moved there. The interesting part is that `resources` has been deleted, but the other keys were not. This indicates that either, kubectl didn't patch the resource correctly, or the flux controller indeed tried to roll back the changes (as suggested by @stefanprodan), but didn't roll back the `resources` key.

Is there some way we could confirm either of both theories?

**Comment by kingdonb** [comment]
> After that, we suspended the kustomization and a manual kubectl apply 

This is not a Flux issue, it's a kubectl issue, and it's not innately clear what should be done when merging the key `resources` from the non-empty etcd source with the file by kubectl apply. The default behavior for this verb in kube API is typically expected to be a merge. If you merge then you retain the values that were there previously

Flux fixes this, Flux's kustomize controller takes care to update the field manager and observe any field managers present to determine if the change is a drift or an appropriate merge, but it requires some hints if you wanted to honor the merge behavior. This is the opposite issue. Kubectl doesn't care about any of that. It will just merge, and if you want to remove those fields you need to explicitly patch them to nil.

It's an issue with server side apply. Here is the test to confirm it, start with a pod definition that has `securityContext` set. Use server side apply to apply it to the cluster like Flux does:

```
# pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: test
      image: busybox:1.28
      command: ['sh', '-c', 'echo "The app is running!" && tail -f /dev/null']
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  volumes:
    - name: config-vol
      configMap:
        name: game-demo
        items:
          - key: log_level
            path: log_level
```

```
$ k apply --server-side -f pod-example.yaml
pod/configmap-pod serverside-applied
```

Then, edit the pod file so it does not have the securityContext field anymore:

```yaml
spec:
  # securityContext: {}
  containers:
```

If you apply the file now with `kubectl apply -f pod.yaml` now, kubectl will use a client-side apply. This works, but doesn't delete the field:

```
$ kubectl apply -f pod-example.yaml
Warning: resource pods/configmap-pod is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
pod/configmap-pod configured
```

Since server-side apply uses managed fields, it doesn't leave this last-applied-configuration breadcrumb. Kubectl apply does not know what to do, and the resulting state in kube API still contains the fields:

```yaml
spec:
...
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
    runAsGroup: 3000
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: default
...
```

If you check the field manager according to kube API now, you will see these fields still have a manager of kubectl (the server-side applier for kubectl)

```
$ kubectl get -oyaml --show-managed-fields pod configmap-pod
```

```yaml
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:containers:
          k:{"name":"test"}:
            .: {}
            f:command: {}
            f:image: {}
            f:name: {}
        f:securityContext:
          f:fsGroup: {}
          f:runAsGroup: {}
          f:runAsUser: {}
    manager: kubectl
    operation: Apply
    time: "2023-09-20T12:35:34Z"
```

Does that explain at all what the source of the trouble is? This took a long time to get exactly right in Flux, (it gets potentially even more complicated when you start merging arrays, this is just a simple example, but believe me it gets much worse...)

I think the suggestion is to file a bug against kubectl, but the prospect of them changing the behavior at this point sounds pretty bleak, if there was something they could do to make it behave more expectedly, then Flux would have to cope with the changes, so I hope the design is intentional and one we can live with 😂
