### ISSUE TITLE
Support Kustomize `labels` property

### ISSUE THREAD

**Issue by merusso** [fluxcd/helm-controller#794]
I'd like to use Kustomize [labels](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/labels/) to set k8s labels across all objects in a Helm release.

According to the [docs](https://fluxcd.io/flux/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Kustomize), `HelmRelease.spec.postRenderers.kustomize` doesn't expose this `labels` property.

For example, I want to set the labels `foo: foo1` and `bar: bar1` on all Helm objects. If I could use the Kustomize `labels` property, I could do the following:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
spec:
  postRenderers:
  - kustomize:
      labels:
        - pairs:
            foo: foo1
            bar: bar1
      includeTemplates: true
```

Otherwise, I would need to perform some kind of patch, which is harder and has some tricky edge cases. Example:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
spec:
  postRenderers:
  - kustomize:
      patchesJson6902:
      # Patch all objects
      # Note: This fails if a Helm template is missing metadata.labels property
      - patch:
        - op: add
          path: /metadata/labels/foo
          value: foo1
        - op: add
          path: /metadata/labels/bar
          value: bar1
        target:
          name: .*
      # Patch Deployment's Pod template
      - patch:
        - op: add
          path: /spec/template/metadata/labels/foo
          value: foo1
        - op: add
          path: /spec/template/metadata/labels/bar
          value: bar1
        target:
          kind: Deployment
          name: .*
```

_Originally posted by @merusso in https://github.com/fluxcd/flux2/discussions/3687_
