### ISSUE TITLE
Helm drift detection causes endless upgrade loop with CRDs

### ISSUE THREAD

**Issue by rsafonseca** [fluxcd/helm-controller#805]
CR objects don't support StrategicMergePatch out of the box in Kubernetes, because their spec isn't builtin.
As a consequence of that, helm applies a MergePatch instead of StrategicMergePatch for CR objects.

The problem:
- Helm-controller drift detection triggers a helm upgrade when there are changes in CR objects
- If spec.upgrade.force is set to false (the default) on the helmrelease, this causes an endless loop because the helm upgrade will not effect any changes (effectively it just compares the previously applied configuration with the would-be-applied configuration, not taking into account the current cluster state

The (easier) solution:
- Helm-controller drift detection should take into account helm's behaviour when upgrading releases and not trigger an upgrade when spec.upgrade.force = false and the modified object is a CR only

Relevant change of helm's code (which was introduced because previously trying to patch CR objects was simply failing): https://github.com/helm/helm/pull/7269/files

**Comment by stefanprodan** [comment]
Use Flux CRD upgrade feature and the drift should be solved, to let Flux manage the CRDs:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-operator
spec:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
```
