### ISSUE TITLE
FEATURE: HelmRelease valueFiles (multiple sources)

### ISSUE THREAD

**Issue by cdenneen** [fluxcd/helm-controller#814]
Currently the only `valueFiles` is at the chart spec. I would like to request the feature be added to add `valueFiles` at the HelmRelease spec level to reside alongside the `values` and `valuesFrom` maps.

The `valueFiles` at the HelmReleaseSpec would allow for passing multiple `-f values.yaml` files to the release. These files would reside in a `GitRepository` `sourceRef` which would allow to overcome the fact that you can't pass multiple files currently, the `valueFiles` in the chart must reside from within the chart itself, doing a kustomize `configMapGenerator` can't merge `values.yaml` because it's a string, `configMapGenerator` doesn't allow for more than `k=v` pairs (no nested YAML). 

This support currently exists in ArgoCD: https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository

**Comment by stefanprodan** [comment]
You can have multiple sources in a `configMapGenerator` like so:

```yaml
configMapGenerator:
  - name: my-values
    files:
      - values1.yaml=values1.yaml
      - values2.yaml=values2.yaml
```

And in the HelmRelease:

```yaml
spec:
  values:
  valuesFrom:
    - kind: ConfigMap
      name: my-values
      valuesKey: values1.yaml
    - kind: ConfigMap
      name: my-values
      valuesKey: values2.yaml
```

**Comment by cdenneen** [comment]
I know this means they need to reside next to release and can’t be referenced from other sources

**Comment by stefanprodan** [comment]
They don't need to to be next to a release, helm-controller gets the values from etcd.

**Comment by cdenneen** [comment]
configMapGenerator has a lot of limitations besides the fact that it puts the yaml into a string. For example when you want to have environment specific or cluster specific values, I can't use `postBuild.substitute` to replace values:

```
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: podinfo-values
  namespace: ${flux_namespace}
files:
  - values.yaml=values.yaml
  - environment.yaml=../../environments/${environment}/addons/podinfo/values.yaml
  - cluster.yaml=../../bootstrap/clusters/${cluster_name}/addons/podinfo/values.yaml
```

So inefficiently you technically can have the following in the release itself:

```
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: podinfo-values
  namespace: ${flux_namespace}
files:
  - values.yaml=values.yaml
  - dev.yaml=../../environments/dev/addons/podinfo/values.yaml
  - qa.yaml=../../environments/qa/addons/podinfo/values.yaml
  - prod.yaml=../../environments/prod/addons/podinfo/values.yaml
```
I lose the ability to have one for each cluster unless I literally wrote out every cluster:

```
files:
...
  - clusterA.yaml=../../clusters/clusterA/addons/podinfo/values.yaml
  - clusterB.yaml=../../clusters/clusterB/addons/podinfo/values.yaml
...
  - clusterZ.yaml=../../clusters/clusterZ/addons/podinfo/values.yaml
```

allowing the `valuesFiles` in the HelmSpec allows to avoid this and since HelmRelease can take advantage of variable substitution the limitation based on configMap generation goes away.

One advantage configMapGenerator has right now that I'm unclear if `valuesFiles` would allow is the variable substitution inside those does work but I'd assume that when HelmRelease ran it should work.

The helm-controller should be able to mount the values.yaml (valuesFiles) from the gitRepo as it does for the release.yaml already in the /tmp/ directories so should be no reason it technically couldn't sourceRef the values files (by default it looks in relative path within same GitRepository it's using for the HelmRelease unless you specify a different GitRepository name and it would be relative to that one.
