### ISSUE TITLE
Improper capitalisation of Helm values when describe helm release

### ISSUE THREAD

**Issue by gaalw** [fluxcd/helm-controller#831]
Good day Sirs!

I am facing multiple times that when I do `kubectl describe` on `HelmRelease` the keys under values are distorted in two ways:

- their first letters are capitalised
- if key has multiple words, they are split by space:

the example:

```bash
gaal@bigsur 01-base-infra % kubectl describe helmrelease -n teleport-cluster-2 teleport
...
Spec:
  Chart:
    Spec:
      Chart:               teleport-cluster
      Reconcile Strategy:  ChartVersion
      Source Ref:
        Kind:   HelmRepository
        Name:   teleport
      Version:  *
  Interval:     1m0s
  Values:
    Acme:          true
    Acme Email:    *****@gmail.com
    Cluster Name:  teleport.*****.***
    Enterprise:    false
    Ingress:
      Enabled:  false
    Rbac:
      Create:  false
    Service:
      Type:  LoadBalancer
```

the original values:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport
  namespace: teleport-cluster-2
spec:
  chart:
    spec:
      chart: teleport-cluster
      sourceRef:
        kind: HelmRepository
        name: teleport
      version: '*'
  interval: 1m0s
  values:
    acme: true
    acmeEmail: *****@gmail.com
    clusterName: teleport.*****.***
    rbac:
      create: false
    ingress:
      enabled: false
    service:
      type: LoadBalancer
    enterprise: false
```

It makes the describe output totally useless for checking if values were set correctly or otherwise. I really wonder if there exists any option to fix it and make describe yielding something like:

```bash
gaal@bigsur 01-base-infra % kubectl describe helmrelease -n teleport-cluster-2 teleport
...
Spec:
  Chart:
    Spec:
      Chart:               teleport-cluster
      Reconcile Strategy:  ChartVersion
      Source Ref:
        Kind:   HelmRepository
        Name:   teleport
      Version:  *
  Interval:     1m0s
  Values:
    acme:          true
    acmeEmail:    *****@gmail.com
    clusterName:  teleport.*****.***
    enterprise:    false
    ingress:
      enabled:  false
    rbac:
      create:  false
    service:
      type:  LoadBalancer
```

so effectively showing values section "AS IS"
