### ISSUE TITLE
Error parsing json string from ConfigMap using valuesFrom in HelmRelease

### ISSUE THREAD

**Issue by antonosmond** [fluxcd/helm-controller#853]
Hi
I have an issue trying to get a JSON string from a ConfigMap into the values using the `valuesFrom` property in a `HelmRelease`.
I did find [this](https://github.com/fluxcd/helm-controller/issues/285) issue however in my case I'm pretty sure I'm using a valid `targetPath` as it's just a root value.

I have a helm chart template with a line like:
```yaml
private_subnet_ids: {{ .Values.private_subnet_ids | fromJsonArray | toYaml | nindent 4 }}
```

If I put a json string directly in the values, the chart renders as expected e.g. I put this in values.yaml:
```yaml
private_subnet_ids: '["subnet-11111111111111111","subnet-22222222222222222","subnet-33333333333333333"]'
```
I run the `helm template` command locally and the chart renders:
```yaml
  private_subnet_ids: 
    - subnet-11111111111111111
    - subnet-22222222222222222
    - subnet-33333333333333333
```
Now I'm trying to populate that value from a ConfigMap. In my ConfigMap I have an identical JSON string e.g.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: example
  namespace: flux-system
data:
  private_subnet_ids: '["subnet-11111111111111111","subnet-22222222222222222","subnet-33333333333333333"]'
```
In my `HelmRelease` I have:
```yaml
  valuesFrom:
    - kind: ConfigMap
      name: example
      valuesKey: private_subnet_ids
      targetPath: private_subnet_ids
```
But I get this error in the `HelmRelease` status:
```
unable to merge value from key 'private_subnet_ids' in ConfigMap 'flux-system/example' into target path 'private_subnet_ids': key "\"subnet-22222222222222222\"" has no value (cannot end with ,)
```
I've tried various versions of quoting & escaping but no luck. What am I doing wrong? Anything I can do to get this to work?
Thanks!
