### ISSUE TITLE
HelmRepository type oci is not having status object

### ISSUE THREAD

**Issue by sebastiangaiser** [fluxcd/helm-controller#866]
Hey,

we implemented the [Flux custom Prometheus metrics](https://fluxcd.io/flux/monitoring/custom-metrics/) and discovered that the status object of HelmRepository with type oci is empty which should be exported as [described here](https://github.com/fluxcd/flux2-monitoring-example/blob/5274d23c2ba3779c75a0ead739a127a91055455a/monitoring/controllers/kube-prometheus-stack/kube-state-metrics-config.yaml#L129).

Steps to reproduce:
```
kubectl apply -f - <<EOF
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/stefanprodan/charts
EOF
```
```
flux get sources helm podinfo
NAME    REVISION        SUSPENDED       READY   MESSAGE                  
podinfo                 False           True    Helm repository is Ready
```
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"source.toolkit.fluxcd.io/v1beta2","kind":"HelmRepository","metadata":{"annotations":{},"name":"podinfo","namespace":"flux-system"},"spec":{"interval":"5m0s","type":"oci","url":"oci://ghcr.io/stefanprodan/charts"}}
  creationTimestamp: "2024-01-09T10:14:40Z"
  generation: 1
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  provider: generic
  type: oci
  url: oci://ghcr.io/stefanprodan/charts
status: {}
```

helm-controller: `Image: ghcr.io/fluxcd/helm-controller:v0.37.2`

For "normal" HelmRepositories this is working fine.
