### ISSUE TITLE
Unable to detect server capabilities

### ISSUE THREAD

**Issue by b4nst** [fluxcd/helm-controller#936]
When trying to deploy [Loki](https://github.com/grafana/loki/tree/0084262269f4e2cb94d04e0cc0d40e9666177f06/production/helm/loki) chart we faced an issue about server capabilities detection.

The relevant part of the chart is
https://github.com/grafana/loki/blob/0084262269f4e2cb94d04e0cc0d40e9666177f06/production/helm/loki/templates/read/hpa.yaml#L2-L8

Trying to deploy with autoscaling enabled, we face:

```trace
no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1" ensure CRDs are installed first
```

However our control plane is returning the correct v2 version for autoscaling:

```shell
kubectl get --raw /apis/autoscaling
```

```json
{
  "kind": "APIGroup",
  "apiVersion": "v1",
  "name": "autoscaling",
  "versions": [
    {
      "groupVersion": "autoscaling/v2",
      "version": "v2"
    },
    {
      "groupVersion": "autoscaling/v1",
      "version": "v1"
    }
  ],
  "preferredVersion": {
    "groupVersion": "autoscaling/v2",
    "version": "v2"
  }
}
```

We're using flux [v2.2.3](https://github.com/fluxcd/flux2/releases/tag/v2.2.3)

---

For reference, this as also been discussed in https://github.com/fluxcd/flux2/discussions/4234

**Comment by stefanprodan** [comment]
Can you please try `ghcr.io/fluxcd/helm-controller:preview-65b54580` this preview image is using the latest Helm SDK v3.14.3

**Comment by hiddeco** [comment]
Is this an installation or an upgrade? In case of the latter, you may be running into something which typically requires https://github.com/helm/helm-mapkubeapis

**Comment by b4nst** [comment]
That's a new installation, I'll give a shoot to the preview image. Thanks for the reactivity!

**Comment by b4nst** [comment]
Still facing the same issue with the `preview-65b54580`. I tried remove and recreate the chart from scratch just in case, but no joy

**Comment by stefanprodan** [comment]
Are you using impersonation in your HelmRelease, do you have `.spec.serviceAccountName` or `.spec.kubeConfig`?

**Comment by souleb** [comment]
can you reproduce this with `helm install`? The capabilities check is performed by the same code in the`helm sdk`. Can you see anything in the log?

**Comment by b4nst** [comment]
Sorry for the delay, I don't impersonate (no `.serviceAccountName` or `.kubeConfig` in the HelmRelease specs). And I cannot reproduce that with manual `helm install`. The manual `helm install` correctly creates an autoscaling/v2 HPA.

**Comment by stefanprodan** [comment]
@b4nst are using the same server with the same values for the Helm CLI as helm-controller? In Flux we call the same install function as the CLI, the capabilities are collected by Helm SDK itself: https://github.com/helm/helm/blob/14d0c13e9eefff5b4a1b511cf50643529692ec94/pkg/action/install.go#L286

**Comment by b4nst** [comment]
Yeah same values, same cluster. I'll check the helm-controller install, maybe it lacks permissions?

**Comment by stefanprodan** [comment]
Can you post here your HelmRepo/HelmRelease YAML so I can try on a fresh cluster please

**Comment by b4nst** [comment]
Sure, I removed some sensitive info but that shouldn't impact the test.

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "3.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    loki:
      storage:
        type: gcs
        bucketNames:
          chunks: foo-loki-chunks
          ruler: foo-loki-ruler
          admin: foo-loki-admin
      schema_config:
        configs:
          - from: 2020-01-01
            store: tsdb
            object_store: gcs
            schema: v13
            index:
              prefix: index_
              period: 24h
    loki_canary:
      enabled: false
    gateway:
      enabled: true
      autoscaling:
        enabled: true
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
```
