### ISSUE TITLE
Changes in postRenderers are ingored

### ISSUE THREAD

**Issue by alex-berger** [fluxcd/helm-controller#964]
Given the below *HelmRelease* with helm-controller v0.37.4:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      version: '>=6.0.0 <7.0.0'
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 1m
      reconcileStrategy: ChartVersion
  upgrade:
    remediation:
      retries: -1
  driftDetection:
    mode: enabled
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: podinfo
                namespace: default
                annotations:
                   hello: world # Changing this line will not trigger an update (unexpected)
  values:
     dummy: x # However, changing this line will trigger an update (expected)
```

# Observed Behavior

Changes to `spec.postRenderers` **will not** trigger an update of the *HelmRelease*. However, changing for example `.spec.values.*` or `spec.chart.spec.*` will trigger an update.  

# Expected Behavior

Changes to `spec.postRenderers` **should** trigger an update of the *HelmRelease*.
