### ISSUE TITLE
Can't seem to install pre-release helmrelease (A.B.C-alpha.N)

### ISSUE THREAD

**Issue by joaocc** [fluxcd/helm-controller#997]
Hi,
Trying to install the alpha version of a chart, using flux 2.2.3 with pre-release patch.

The following helm command runs well on cli.
```
helm upgrade --dry-run vcp vcluster-platform --install --repo https://charts.loft.sh/  --version 4.0.0-alpha.5 --namespace test-vcp
```
However, when I try to install via flux, with the following config snippets, I get an error:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loft-sh.vcluster
  # name: vcluster
  namespace: flux-system
spec:
  interval: 25h
  url: https://charts.loft.sh
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcp
  namespace: test-vcp
spec:
  interval: 5m
  chart:
    spec:
      chart: vcluster-platform
      version: "4.0.0-alpha.5"
      sourceRef:
        kind: HelmRepository
        name: loft-sh.vcluster
        namespace: flux-system
      interval: 5h
...
```
```
Message
invalid chart reference: failed to get chart version for remote reference: no 'vcluster-platform' chart with version matching '4.0.0-alpha.5' found
Reason
InvalidChartReference
```
Besides the manual helm command running well, the manual inspection of `index.yaml` and downloading the tgz all seem to work.
Is there any flag that prevents the specification of pre-release releases?
Any ideas?
Thx
